# -*- makefile -*-
# This file specifies where Munin will look for things after you've
# run 'make' in the source directory.  Modify it to suit your needs.

# DESTDIR is meant only for use when making Munin packages.  Unless
# you're doing packaging do NOT set it.
# DESTDIR is empty during building, and optionally set to point to
# a shadow tree during make install.

# Note: There is a need for a VARDIR, with DBDIR, PLUGSTATE, HTMLDIR
# and LOGDIR as subdirectories.  Today, DBDIR contains configured
# domains, as well as PLUGSTATE, and we risk collisions.

#
# the base of the Munin installation.
#
PREFIX     = $(DESTDIR)

# Where Munin keeps its configurations (server.conf, client.conf, ++)
CONFDIR    = $(DESTDIR)/etc/munin

# Server only - where to put munin-cron
BINDIR     = $(PREFIX)/usr/bin

# Client only - where to put munin-node, munin-node-configure, and munin-run
SBINDIR    = $(PREFIX)/usr/bin

# Where to put text and html documentation
DOCDIR     = $(PREFIX)/usr/share/doc/munin

# Where to put man pages
MANDIR     = $(PREFIX)/usr/share/man

# Where to put internal binaries and plugin repository
LIBDIR     = $(PREFIX)/usr/lib/munin

# Server only - Output directory
HTMLDIR    = $(PREFIX)/usr/share/munin/www
CGIDIR     = $(PREFIX)/usr/share/munin/cgi

# Where to put internal data for master (RRD, internal files, ...)
DBDIR      = $(DESTDIR)/var/lib/munin

# Where to put internal data for node (plugin state, ...)
DBDIRNODE  = $(DESTDIR)/var/lib/munin

# Client only - Where the spool files are written. Must be writable by
# group "munin", and should be preserved between reboots
SPOOLDIR   = $(DBDIR)/spool

# Client only - Where plugins should put their states. Must be writable by
# group "munin", and should be preserved between reboots
PLUGSTATE  = $(DBDIRNODE)/plugin-state

# Where Munin should place its logs.
LOGDIR     = $(PREFIX)/var/log/munin

# Location of PID files and other statefiles. On the server, must be
# writable by the user "munin".
STATEDIR   = $(DESTDIR)/run/munin

# The perl interpreter to use
PERL       := /usr/bin/perl

# The python interpreter to use (used by some plugins)
PYTHON     := /usr/bin/env python2

# The ruby interpreter to use (used by some plugins)
RUBY       := /usr/bin/env ruby

# The java runtime to use (used by some plugins)
JAVARUN    := /usr/bin/java

# The java library dir to use (used by some plugins)
# this is needed in order to be able to install
# java libraries in a custom location. Many distrubutions
# enforce a spesific location for java libraries.
JAVALIBDIR:= $(LIBDIR)


# A modern (posix) shell.  We're not looking for arrays, but $() and
# other modern stuff is expected.  On a posix-system the expression
# below will find the right shell.  Most Unixes released the last 10
# years are POSIX compliant enough for this to work (he said bravely).
#
# On Linux /bin/sh, SunOS/Solaris /usr/xpg4/bin/sh or /bin/ksh
# In general: bash or ksh will work
#
GOODSH     := /bin/sh

# Path of bash for bash specific plugins
BASH       := /bin/bash

# Server only - Where to install the perl libraries
PERLSITELIB := $(shell $(PERL) -V:vendorlib | cut -d"'" -f2)
PERLLIB    = $(DESTDIR)$(PERLSITELIB)

# Client only - Install plugins for this architecture
OSTYPE     := $(shell uname | tr '[A-Z]' '[a-z]')

# How to figure out the hostname. (Only used in default configuration
# files)
HOSTNAME   := myhostname

# What is the safest way to create a tempfile.
# Default is to figure it out by testing various methods.
# Replace this with a known platform-specific method
MKTEMP     := $(shell ./test-mktemp)

# Munin version number.
VERSION    := $(shell ./getversion)

# User to run munin as
USER       := munin
GROUP      := munin

# Default user to run the plugins as
PLUGINUSER := nobody

# Default user to run the cgi as
CGIUSER := nobody

# Which command to use to check if the USER and GROUP to run Munin as, exists.
GETENT     := /bin/true
CHECKUSER  := /bin/true
CHECKGROUP := /bin/true

CHOWN      := true
CHMOD      := chmod
CHGRP      := true

# Java compiler stuff - only needed on the buildhost
JC         := javac
JFLAGS     := -g -source 1.5 -target 1.5
JAR        := jar

# Check if the java compiler works
JCVALID    := no

# Check whether setruid functionality can be used
HASSETR    := $(shell perl -e 'use Config; my @vars=("d_setruid", "d_setreuid", "d_setresuid"); foreach my $$var (@vars) { if ($$Config{$$var} eq "define") { print "1\n"; exit 0; } } print "0\n"; exit 0;' )
