post_install () {
  # Check user/group munin exists
  getent group munin >/dev/null || groupadd munin
  getent passwd munin >/dev/null || useradd -c "Munin system monitor" -g munin -s /bin/false -d /var/lib/munin munin
  # Fix permissions
  chown munin.munin -R /var/log/munin /var/lib/munin /var/run/munin
  # Display cron command
  echo "See the example cron entry (for the munin user) for further setup:
    /etc/munin/munin-cron-entry"
}
