post_install () {
  # Do basic configuration
  echo "==> Run the following to get a good set of default plugins:"
  echo "    munin-node-configure --shell | sh"
  post_upgrade
}

post_upgrade() {
  # Ensure directories exist
  mkdir -p /var/{lib,log}/munin /run/munin
  # Fix permissions on necessary directories
  chown munin.munin /var/{lib,log}/munin /run/munin
  chown munin.munin /var/lib/munin/spool
  chown munin.munin /var/lib/munin/plugin-state
}
