#!/bin/bash

CONFIG_FILE='/etc/arptables.conf'

case $1 in
  start)
    arptables-restore < "$CONFIG_FILE"
  ;;
  stop)
    arptables-restore < /dev/null
  ;;
  save)
    arptables-save > "$CONFIG_FILE"
  ;;
  *)
    echo "usage: ${0##*/} {start|stop|save}" >&2
    exit 1
  ;;
esac

# vim:set ts=2 sw=2 ft=sh et:
