#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Mounting NFS filesystems"
    if [ ! -f /var/run/daemons/portmap ]; then
      stat_fail
			echo "ERROR: portmap is not running"
      exit 1
    fi
    mount -a -t nfs
    add_daemon nfsmount
    stat_done
    ;;
  stop)
    stat_busy "Unmounting NFS filesystems"
    umount -a -t nfs
    sleep 1
    if [ ! -z `mount -t nfs` ]; then
      stat_fail
      exit 1
    fi
    rm_daemon nfsmount
    stat_done
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
