#!/bin/sh
test -e /usr/lib/libgcr-base-3.so.1  && exec /usr/bin/pinentry-gnome3 "$@"
test -e /usr/lib/libQt5Widgets.so.5  && exec /usr/bin/pinentry-qt     "$@"
test -e /usr/lib/libgtk-x11-2.0.so.0 && exec /usr/bin/pinentry-gtk-2  "$@"
exec /usr/bin/pinentry-curses "$@"
