post_install() {
  cat << MES
>>> See the wiki at http://wiki.archlinux.org/index.php/PulseAudio for details
    on configuring your system for PulseAudio.

>>> Make sure to install pulseaudio-alsa to configure ALSA for PulseAudio.
MES
}

post_upgrade() {
  # Delete old users and groups
  # System-wide daemon not supported anymore
  if (( $(vercmp $2 0.9.22) < 0 )); then
    getent passwd pulse &>/dev/null && usr/sbin/userdel -f pulse
    getent group pulse-access &>/dev/null && usr/sbin/groupdel pulse-access
    getent group pulse-rt &>/dev/null && usr/sbin/groupdel pulse-rt
    getent group pulse &>/dev/null && usr/sbin/groupdel pulse
  fi

  true
}

# vim:set ts=2 sw=2 et:
