post_install() {
    EXTRAMODULES='extramodules-3.16-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-3.16-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    if  [ "$(vercmp $2 340.22-2)" -lt 0 ]; then
        echo 'If your card is from the 2xx series or earlier, install nvidia-340xx'
    fi
}

post_remove() {
    EXTRAMODULES='extramodules-3.16-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
