#!/bin/bash

build() {
    add_module btrfs
    add_binary btrfs
    add_runscript

    add_file /usr/lib/udev/rules.d/70-btrfs.rules
}

help() {
    cat <<HELPEOF
This hook provides support for multi-device btrfs volumes.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
