post_install() {
  echo "==> If you want to use syslinux as your BIOS bootloader"
  echo "==> edit /boot/syslinux/syslinux.cfg and run"
  echo "==>   # /usr/bin/syslinux-install_update -i -a -m"
  echo "==> to install it."
  
  cat << EOF
Syslinux efi64 and efi32 files have been installed at
/usr/lib/syslinux/{efi64,efi32}/ respectively.

To install, copy /usr/lib/syslinux/efi64 to (ESP)/EFI/syslinux and
syslinux.cfg to (ESP)/EFI/syslinux/syslinux.cfg and add a boot entry
using efibootmgr for (ESP)/EFI/syslinux/syslinux.efi
EOF

}

post_upgrade() {
  # auto-update syslinux if /boot/syslinux/SYSLINUX_AUTOUPDATE exists
  /usr/bin/syslinux-install_update -s
  # update to 5.01 message
  if [ "$(vercmp $2 5.01)" -lt 0 ]; then
      echo "If you used syslinux-install_update to install syslinux:"
      echo "==> If you want to use syslinux with menu and all modules please rerun" 
      echo "==>   # /usr/bin/syslinux-install_update -i -a -m"
      echo ""
      echo "If you manually installed syslinux:"
      echo "==> Please copy or symlink all .c32 modules to your /boot/syslinux directory."
      echo "==> If (/ and /boot on seperate fs):"
      echo "==>   # cp /usr/lib/syslinux/*.c32 /boot/syslinux"
      echo "==> If (/ and /boot on same fs):"
      echo "==>   # ln -s /usr/lib/syslinux/*.c32 /boot/syslinux"
  fi
}

# vim:set ts=2 sw=2 et:
