# $Id: smb4k.install,v 1.1 2007/11/20 03:09:26 travis Exp $
# arg 1:  the new package version
post_install() {
    echo "==> Note: To enable mounting and unmounting of smb/cifs shares as"
    echo "==> user, you will need to issue the following commands as root:"
    echo "# chmod +s \$(which mount.cifs) \$(which umount.cifs)"
    echo "# chmod +s \$(which smbmnt) \$(which smbumount)"
    echo "==> These commands will need to be re-run every upgrade of smbclient"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
    post_install $1 
}

op=$1
shift
$op $*
