#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/deluged

[[ -f /var/run/deluged.pid ]] && PID=$(cat /var/run/deluged.pid)
[[ -d /proc/$PID ]] || PID=

case "$1" in
  start)
    stat_busy "Starting Deluge Daemon"
    [[ -z $PID ]] && su -l -s /bin/sh -c "/usr/bin/deluged >/dev/null" $DELUGE_USER
    if [ $? -gt 0 ]; then
      stat_fail
    else
      sleep 1
      echo $(pgrep -u $DELUGE_USER deluged) > /var/run/deluged.pid
      add_daemon deluged
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Deluge Daemon"
    [[ ! -z $PID ]] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/deluged.pid
      rm_daemon deluged
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0

