PKGNAME=wicd

pre_remove () {
    for pyo in $(pacman -Qql $PKGNAME  | grep \.py$ | sed 's|.py$|.pyo|g'); do
        if [ -f "$pyo" ]; then
            rm "$pyo"
        fi
    done
}

post_install() {
  echo
  echo "==> You need to restart the dbus service after "
  echo "==> upgrading wicd."
  echo "==> Disable networkmanager,dhcdbd or other networking " 
  echo "==> utility and add 'wicd' to your systemd configuration."
  echo
  echo "==> To run: wicd-cli or wicd-curses"    
}
