pkgname=gnome-panel

post_install() {
  gconfpkg --install $pkgname
  glib-compile-schemas /usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  gconfpkg --uninstall $pkgname
}

post_remove() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}
