#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/deluged

[[ -f /var/run/deluge-web.pid ]] && PID=`cat /var/run/deluge-web.pid`

case "$1" in
  start)
    stat_busy "Starting Deluge WebUI"
    [[ -z $PID ]] && su -l -c "/usr/bin/deluge-web -f" $DELUGE_USER
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $(pgrep deluge-web) > /var/run/deluge-web.pid
      add_daemon deluge-web
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Deluge WebUI"
    [[ ! -z $PID ]] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/deluge-web.pid
      rm_daemon deluge-web
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
