# kvm:  the new package version
post_install() {
  #
  groupadd kvm -f -g 78
  echo ">>> Qemu package now provides standard qemu and qemu-kvm."
  echo ""
  echo ">>> PLEASE READ FOR KVM USAGE!"
  echo ">>>  Load the correct KVM module, you will need a KVM capable CPU!"
  echo ">>>  Add yourself to the group 'kvm'."
  echo ">>>  Use 'qemu-kvm' to use KVM."
  echo ""
  echo ">>> 'qemu-kvm' flexibility:"
  echo ">>>  You can use the qemu-kvm binary without kvm module too."
  echo""
  echo ">>> PLEASE READ FOR KQEMU USAGE!"
  echo ">>> You need to install the 'kqemu' package for your kernel."
  echo ">>> You need to load the module to use qemu with kqemu."

  /bin/true
}

post_upgrade() {
  post_install $1
}

post_remove() {
  #
  groupdel kvm
  #
  depmod -a
  #
  /bin/true
}

op=$1
shift
$op $*
