post_install() {

gtk-update-icon-cache -f -q /usr/share/icons/hicolor
update-desktop-database -q

echo " * relogin or source /etc/profile.d/openoffice.sh"
echo " * see http://wiki.archlinux.org/index.php/Openoffice"
echo "   how to use extensions, e.g. for spell checking"
echo "   see /opt/openoffice/share/extension/install what"
echo "   is shipped with this package"
}

post_upgrade() {
  post_install $1
}

post_remove() {
update-desktop-database -q
gtk-update-icon-cache -f -q /usr/share/icons/hicolor

# make sure everything is gone, maybe someone has installed
# extensions for all users using unopkg --shared
rm -rf /opt/openoffice
}

