post_install() {
 echo ">> If you use an HTTPS connection to CUPS, the first time you access"
 echo ">> the interface it may take a very long time before the site comes up."
 echo ">> This is because the first request triggers the generation of the CUPS"
 echo ">> SSL certificates which can be a very time-consuming job."
}

post_upgrade() {
  # FS#56818 - make sure we change the ownership to the new cups group
  if [[ $(vercmp 2.2.6-2 $2) = 1 ]]; then
    chgrp -R 209 /etc/cups
  fi
}

