PKGNAME="texlive-core"
UPDMAP="/etc/texmf/web2c/updmap.cfg"
SYNCWITHTREES=''
NEWMAPS=`mktemp`
cat <<EOF > $NEWMAPS
Map euler.map
Map charter.map
Map fpls.map
Map l7x-urwvn.map
Map lm.map
Map marvosym.map
Map pazo.map
Map pxfonts.map
Map qag.map
Map qbk.map
Map qcr.map
Map qcs.map
Map qhv.map
Map qpl.map
Map qtm.map
Map qzc.map
Map tabvar.map
Map txfonts.map
Map utopia.map
Map zpeu.map
MixedMap ccpl.map
MixedMap cm-super-t1.map
MixedMap cm-super-t2a.map
MixedMap cm-super-t2b.map
MixedMap cm-super-t2c.map
MixedMap cm-super-ts1.map
MixedMap cm-super-x2.map
MixedMap cm.map
MixedMap cmextra.map
MixedMap cmtext-bsr-interpolated.map
MixedMap csother.map
MixedMap cstext.map
MixedMap cyrillic.map
MixedMap eurosym.map
MixedMap latxfont.map
MixedMap mflogo.map
MixedMap plother.map
MixedMap pltext.map
MixedMap rsfs.map
MixedMap stmaryrd.map
MixedMap symbols.map
MixedMap tipa.map
MixedMap wasy.map
MixedMap yhmath.map
EOF

pre_install() {
	cat $NEWMAPS >> $UPDMAP
}

post_install() {
	echo    ">>> texlive: updating the filename database..."
	/usr/bin/mktexlsr
	echo    ">>> texlive: updating the fontmap files with updmap..."
	/usr/bin/updmap-sys --quiet --nohash
	echo    " done." 
  echo -n   "creating all formats..."
  /usr/bin/fmtutil-sys --all 1>/dev/null
  echo      " done." 
  echo      " (logs are under /var/lib/texmf/web2c/<engine>/<formatname>.log)"
}

pre_upgrade() {
  if [[ "$2" == 200* ]]; then
    OLDMAPS="/usr/share/texmf-var/arch/installedpkgs/$PKGNAME.maps"
    echo "Info: copying previous updmap.cfg from /usr/share/texmf-config/web2c/"
    echo "      to /etc/texmf/web2c/ (and keeping new one as updmap.cfg.pacnew)"
    mv /etc/texmf/web2c/updmap.cfg /etc/texmf/web2c/updmap.cfg.pacnew 
    cp /usr/share/texmf-config/web2c/updmap.cfg.pacsave /etc/texmf/web2c/updmap.cfg
  else # $2 >= 2010
    OLDMAPS="/var/lib/texmf/arch/installedpkgs/$PKGNAME.maps"
  fi
  if [ -f $OLDMAPS ] ; then
    MAPSDIFF=`mktemp`
    TOADD=`mktemp`
    diff -B $OLDMAPS $NEWMAPS | sed 's/\s\+/ /g' > $MAPSDIFF
    TOREMOVE=`cat $MAPSDIFF | egrep '^<' | cut -d' ' -f3`
    cat $MAPSDIFF | egrep '^>' | sed 's/^> //' > $TOADD
    if [ "x$TOREMOVE" != "x" ]; then
      for map in $TOREMOVE; do
        sed -i "/\s$map/d" $UPDMAP
      done
    fi
    if [ -s $TOADD ]; then
       cat $TOADD >> $UPDMAP
    fi
  else
    echo "Warning: file $OLDMAPS not found" 
    SYNCWITHTREES="--syncwithtrees"
  fi
}

post_upgrade() {
	echo    ">>> texlive: updating the filename database..."
	/usr/bin/mktexlsr
	echo    ">>> texlive: updating the fontmap files with updmap..."
	/usr/bin/updmap-sys --quiet --nohash $SYNCWITHTREES
	echo    " done." 
  echo    ">>> texlive: recreating all formats..."
  /usr/bin/fmtutil-sys --all 1>/dev/null
  echo      " done." 
  echo      " (logs are under /var/lib/texmf/web2c/<engine>/<formatname>.log)"
  if [[ "$2" == 200* ]]; then
    echo      "Important note. Some directories have moved:"
    echo      " \$TEXMFSYSVAR    is now /var/lib/texmf (previously /usr/share/texmf-var)"
    echo      " \$TEXMFSYSCONFIG is now /etc/texmf     (previously /usr/share/texmf-config)"
    echo      "Please move and update the config files you had modified and delete the rest."
    echo      "(Note however that updmap.cfg has been automatically copied and updated.)"
  fi
}

