post_install() {
  rm -f usr/lib/xorg/modules/libwfb.so
  ln -sf libwfb.so.1.4 usr/lib/xorg/modules/libwfb.so

  cmp usr/lib/xorg/modules/extensions/libdri.so usr/lib/xorg/modules/extensions/libglx.xorg >/dev/null && rm -f usr/lib/xorg/modules/extensions/libdri.so

  # If the symlink is dead or non-existent, remove it and make a new one
  if [ ! -e usr/lib/xorg/modules/extensions/libdri.so ]; then
    rm -f usr/lib/xorg/modules/extensions/libdri.so
    ln -sf libdri.xorg usr/lib/xorg/modules/extensions/libdri.so
  fi
}

post_upgrade() {
  post_install
}

post_remove() {
  rm -f /usr/lib/xorg/modules/libwfb.so

  # If the symlink is dead, remove it
  if [ ! -e usr/lib/xorg/modules/extensions/libdri.so ]; then
    rm -f usr/lib/xorg/modules/extensions/libdri.so
  fi
}
