post_install() {
  KERNEL_VERSION='2.6.31-ARCH'
  depmod -v $KERNEL_VERSION  > /dev/null 2>&1
  echo "if you are running kms in early mode please rebuild your initrd"
}

post_upgrade() {
  post_install $1
  rmmod nouveau || echo 'In order to use the new nouveau module, exit Xserver and unload it manually.'
}

post_remove() {
  KERNEL_VERSION='2.6.31-ARCH'
  depmod -v $KERNEL_VERSION	 > /dev/null 2>&1	 
}

