#!/bin/bash

set +e

[[ $# -lt 1 ]] && { echo "Usage: $0 <dir>"; exit 1; }

[[ ! -d $1 ]] && { echo "Not a directory: $1"; exit 1; }

for i in $1/*[^~,] ; do
	[[ $i = *.pacorig ]] && continue
	[[ $i = *.pacsave ]] && continue
	[[ $i = *.pacnew ]] && continue
	[[ $i = *.swp ]] && continue
	[[ $i = *,v ]] && continue
	[[ -d $i ]] && continue
	[[ -x $i ]] && $i 2>&1 | awk "(NR==1) {print \"$i:\n\"} {print}"
done

exit 0
