post_install(){
  groupadd -g 89 mysql &>/dev/null
  useradd -u 89 -g mysql -d /var/lib/mysql -s /bin/false mysql &>/dev/null
  usr/bin/mysql_install_db --datadir=/var/lib/mysql --user=mysql
  chown -R mysql:mysql var/lib/mysql &> /dev/null
  chown mysql:mysql var/run/mysqld &> /dev/null
}

post_upgrade(){
  chown -R mysql:mysql var/lib/mysql &> /dev/null
  chown mysql:mysql var/run/mysqld
}

post_remove(){
  userdel mysql &>/dev/null
  groupdel mysql &>/dev/null
}
