post_install() {
  echo "--------------------------------------------------"
  echo "NOTE: DansGuardian is NOT free for commercial use."
  echo "      See http://dansguardian.org for details on"
  echo "      setup, configuration, and licensing."
  echo "--------------------------------------------------"
  chown -R proxy.proxy var/log/dansguardian 
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  /bin/ture
}

post_remove() {
  /bin/ture
}

op=$1
shift

$op $*
# vim: ts=2 sw=2 et ft=sh
