post_install() {
if [ ! -f /boot/grub/grub.cfg ]; then
 echo -n "Generating grub.cfg.example config file... "
 grub-mkconfig -o /boot/grub/grub.cfg.example 2> /dev/null
 echo "done."
fi
cat << EOF 
 An example config file is created at /boot/grug/grub.cfg.example
 
 For more information and additional config settings please see http://wiki.archlinux.org/index.php/GRUB2

EOF

}


post_upgrade() {
        post_install
}

