pkgname=networkmanager-openconnect

post_install() {
  getent group nm-openconnect >/dev/null 2>&1 || groupadd -g 104 nm-openconnect
  getent passwd nm-openconnect > /dev/null 2>&1 || useradd -u 104 -s /sbin/nologin -d / -M -c 'NetworkManager user for OpenConnect' -g nm-openconnect nm-openconnect
  passwd -l nm-openconnect > /dev/null
}

post_upgrade() {
  post_install
}

post_remove() {
  getent passwd nm-openconnect >/dev/null 2>&1 && userdel nm-openconnect
  getent group nm-openconnect >/dev/null 2>&1 && groupdel nm-openconnect
}
