post_install() {
  echo "PLEASE NOTE:" 
  echo "For these drivers to work, you must install kernel modules." 
  echo "Depending on your kernel, these module packages are named"
  echo "catalyst-\$kernel and stock kernel module is catalyst"
  echo "--------------------------------------------------------------"
  echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
  echo "Remember to add fglrx to the MODULES list in /etc/rc.conf."
  echo "--------------------------------------------------------------"

  rm -f usr/lib/xorg/modules/extensions/libdri.so
  ln -sf libdri.ati usr/lib/xorg/modules/extensions/libdri.so
}

post_upgrade() {
  rm -f usr/lib/xorg/modules/extensions/libdri.so
  ln -sf libdri.ati usr/lib/xorg/modules/extensions/libdri.so
}

post_remove() {
  # If the symlink is dead, remove it
  if [ ! -e usr/lib/xorg/modules/extensions/libdri.so ]; then
    rm -f usr/lib/xorg/modules/extensions/libdri.so
    ln -sf libdri.xorg usr/lib/xorg/modules/extensions/libdri.so
  fi
}
