_source='http://fpdownload.macromedia.com/get/flashplayer/current/install_flash_player_10_linux.tar.gz'

post_install() {
	echo 'Downloading Flash Player...'
	wget -T 10 -q -O - "${_source}" | bsdtar --strip-components=1 -x -o -f - -C usr/lib/mozilla/plugins/ *libflashplayer.so \
		|| echo 'Download failed. Please install again later.'
}

post_upgrade() {
	post_install
}

post_remove() {
	rm -f usr/lib/mozilla/plugins/libflashplayer.so	
}
