_source='http://download.macromedia.com/pub/labs/flashplayer10/libflashplayer-10.0.d20.7.linux-x86_64.so.tar.gz'

post_install() {
	echo 'Downloading Flash Player...'
	wget -T 10 -q -O - "${_source}" | bsdtar -x -o -f - -C usr/lib/mozilla/plugins/ libflashplayer.so \
		|| echo 'Download failed. Please install again later.'
}

post_upgrade() {
	post_install
}

post_remove() {
	rm -f usr/lib/mozilla/plugins/libflashplayer.so	
}
