post_install() {
  getent group hal >/dev/null || usr/sbin/groupadd -g 82 hal
  getent group optical >/dev/null || usr/sbin/groupadd -g 93 optical
  getent group floppy >/dev/null || usr/sbin/groupadd -g 94 floppy
  getent group storage >/dev/null || usr/sbin/groupadd -g 95 storage
  getent passwd hal >/dev/null || usr/sbin/useradd -c 'HAL daemon' -u 82 -g hal -G optical,floppy,storage -d '/' -s /bin/false hal
  usr/bin/passwd -l hal &>/dev/null
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
post_remove() {
  if getent passwd hal &>/dev/null; then
    usr/sbin/userdel hal
  fi
  if getent group hal &>/dev/null; then
    usr/sbin/groupdel hal
  fi
}
