#!/bin/bash

build() {
    MODULES=" dm-mod dm-mirror "
    BINARIES="dmraid dmsetup"
    SCRIPT="dmraid"

    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
}

help() {
  cat <<HELPEOF
This hook loads the necessary modules for a dmraid root device.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
