# arg 1:  the new package version
post_install() {
  scrollkeeper-update -p var/lib/scrollkeeper
  /bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  scrollkeeper-update -p var/lib/scrollkeeper
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
  scrollkeeper-update -p var/lib/scrollkeeper
  /bin/true
}

op=$1
shift
$op $*
