post_install() {
    getent group wireshark >/dev/null 2>&1 ||  usr/sbin/groupadd -g 150 wireshark &>/dev/null

    setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' usr/bin/dumpcap
    echo "NOTE: To run wireshark as normal user you have to add yourself into wireshark group"
}

post_upgrade() {
    post_install $1
}

post_remove() {
    if getent group wireshark >/dev/null 2>&1; then
        groupdel wireshark
    fi
}
