# this is the scrollkeeper handling sample file

post_install() {
  cat << EOM

  --> the console based tools for pdf2* conversion are now in the poppler package

EOM
  echo -n "update desktop mime database..."
  update-desktop-database -q
  echo "done"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  echo -n "update desktop mime database..."
  update-desktop-database -q
  echo "done"
}

op=$1
shift

$op $*
