--- Makefile-orig	2003-09-18 23:01:03.000000000 -0400
+++ Makefile	2003-09-18 23:01:51.000000000 -0400
@@ -12,7 +12,7 @@
 #uncomment the following if you need libpcap based build under linux
 #(not raccomanded)
 COMPILE_TIME= 
-INSTALL_MANPATH=/usr/man
+INSTALL_MANPATH=$(prefix)/man
 
 
 OBJ=	main.o getifname.o getlhs.o \
@@ -55,9 +55,8 @@
 	-(cd utils; $(MAKE) clean)
 
 install: hping2
-	cp -f hping2 /usr/sbin/
-	chmod 755 /usr/sbin/hping2
-	ln -sf /usr/sbin/hping2 /usr/sbin/hping
+	cp -f hping2 $(prefix)/sbin/
+	chmod 755 $(prefix)/sbin/hping2
 	@if [ -d ${INSTALL_MANPATH}/man8 ]; then \
 		cp ./docs/hping2.8 ${INSTALL_MANPATH}/man8; \
 		chmod 644 ${INSTALL_MANPATH}/man8/hping2.8; \
