#!/bin/bash

# This script will create static system-critical device nodes in your /dev
# tree so the initscripts can get by without devfs/udev long enough to start
# up devfs/udev.

STARTDIR=`pwd`
TMPDIR=`mktemp -d`
ROOT=/
[ "$1" != "" ] && ROOT=$1

mount --bind $ROOT $TMPDIR
cd $TMPDIR

echo -n "creating device nodes: "
rm -f dev/console
rm -f dev/null
rm -f dev/zero
mknod dev/console c 5 1
echo -n "console "
mknod -m 666 dev/null c 1 3
echo -n "null "
mknod -m 666 dev/zero c 1 5 
echo -n "zero "
echo

cd $STARTDIR
umount $TMPDIR
rm -rf $TMPDIR
