post_install() {
    EXTRAMODULES='extramodules-3.3-ARCH'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
    echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-3.3-ARCH'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-3.3-ARCH'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}
