# arg 1:  the new package version
post_install() {
  echo "==> xfig has a frontend to transfig. If you want to use this frontend to convert fig files, you need 'transfig'"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  echo "==> xfig has a frontend to transfig. If you want to use this frontend to convert fig files, you need 'transfig'"
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
