post_upgrade() {
  if (($(vercmp $2 0.7.1-2) < 0)); then
    echo ':: Keyboard layouts are now configured through xfce4-keyboard-settings'
    echo '   and managed by xfsettingsd. This plugin now only acts as a layout'
    echo '   indicator and manages per window/application layout preferences.'
    echo
    echo '   You will need to reconfigure the keyboard layouts on your next login.'
  fi
}

# vim:set ts=2 sw=2 et:
