post_install() {
	useradd -d /var -M -r -U kdm &> /dev/null
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_upgrade() {
	getent passwd kdm >/dev/null 2>&1 || useradd -d /var -M -r -U kdm &> /dev/null
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_remove() {
	if getent passwd kdm >/dev/null 2>&1; then
	  userdel kdm
	fi
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}
