# arg 1:  the new package version
post_install() {
  cat << EOM

--> autopano-sift was replaced by auto-pano-sift-c and became a hard dependency
--> in order to make the experienc less painful and confusing. Same deal with
--> enblend which turned into enblend-enfuse. Too much functionality would be
--> missing without those packages.
--> CHECK YOUR PREFERENCES to get rid of any old binary names.

EOM
  echo "update desktop mime database..."
  update-desktop-database -q
}

post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
post_remove() {
  echo "update desktop mime database..."
  update-desktop-database -q
}

op=$1
shift
$op $*
# vim: ft=sh
