pkgname=ghc

pre_upgrade() {
    cat << EOF
    ==> Unregistering cabalized packages...
EOF
    for unreg in /usr/share/haskell/*/unregister.sh; do "$a"; done
    cat << EOF
    ==> Done.
EOF
    
}

post_upgrade() {
    cat << EOF
    ==> All cabalized and yaourt-installed packages need to be reinstalled now.
    ==> See /usr/share/haskell/ and ghc-pkg list --user for a tentative list of affected packages.
EOF
}
