post_install() {
  getent group postgres >/dev/null || groupadd -g 88 postgres
  getent passwd postgres >/dev/null || useradd -c 'PostgreSQL user' -u 88 -g postgres -d '/var/lib/postgres' -s /sbin/nologin postgres
  passwd -l postgres >/dev/null
}

post_upgrade() {
  post_install $1
}

post_remove() {
  getent passwd postgres >/dev/null && userdel postgres
  getent group postgres >/dev/null && groupdel postgres
}
