#!/bin/sh
if [ ! "$1" -a ! "$2" ]; then
  echo "Usage: $0 output.schemas file1.schemas [file2.schemas [...]]"
  exit 1
fi

OUTFILE="$1"
shift

echo '<?xml version="1.0"?>' > "$OUTFILE"
echo '<gconfschemafile><schemalist>' >> "$OUTFILE"

while [ "$1" ]; do
  if [ -f "$1" ]; then
    sed -e '/<?xml/d' -e 's|<gconfschemafile>||g' -e 's|</gconfschemafile>||g' \
        -e 's|<schemalist>||g' -e 's|</schemalist>||g' \
          "$1" >> "$OUTFILE"
  fi
  shift
done
  
echo '</schemalist></gconfschemafile>' >> "$OUTFILE"
