export LC_ALL=C

post_install() {
	usr/bin/update-ca-trust
}

pre_upgrade() {
	if (( $(vercmp $2 20140923-2) < 0 )); then
		find /etc/ssl/certs -type l -print | while read symlink; do
			case $(readlink $symlink) in
			/usr/share/ca-certificates*) rm -f $symlink;;
			esac
		done
		find /etc/ssl/certs -type l -print | while read symlink; do
			test -f $symlink || rm -f $symlink
		done
		rm -f /etc/ssl/certs/ca-certificates.crt
	fi
}

post_upgrade() {
	usr/bin/update-ca-trust
}

pre_remove() {
	usr/bin/update-ca-trust
}

# vim:set noet ts=8 sw=8:
