PKGNAME="texlive-core"
UPDMAP="etc/texmf/web2c/updmap.cfg"
SYNCWITHTREES=''
OLDMAPSSAVE=`mktemp`
NEWMAPS="var/lib/texmf/arch/installedpkgs/$PKGNAME.maps"

post_install() {
  echo    ">>> texlive: updating updmap.cfg with new map files..."
  cat "$NEWMAPS" >> $UPDMAP
  echo    ">>> texlive: updating the filename database..."
  usr/bin/mktexlsr
  echo    ">>> texlive: updating the fontmap files with updmap..."
  usr/bin/updmap-sys --quiet --nohash
  echo    " done." 
  echo -n   "creating all formats..."
  usr/bin/fmtutil-sys --all 1>/dev/null
  echo      " done." 
  echo      " (logs are under /var/lib/texmf/web2c/<engine>/<formatname>.log)"
  echo    "NB: To setup ConTeXt and the lua(la)tex font db,"
  echo    "    see http://wiki.archlinux.org/index.php/TeX_Live"
}

pre_upgrade() {
  if [[ "$2" == 200* ]]; then
    OLDMAPS="usr/share/texmf-var/arch/installedpkgs/$PKGNAME.maps"
    echo "Info: copying previous updmap.cfg from /usr/share/texmf-config/web2c/"
    echo "      to /etc/texmf/web2c/ (and keeping new one as updmap.cfg.pacnew)"
    mv etc/texmf/web2c/updmap.cfg /etc/texmf/web2c/updmap.cfg.pacnew 
    cp usr/share/texmf-config/web2c/updmap.cfg.pacsave etc/texmf/web2c/updmap.cfg
  else
    # $2 >= 2010
    OLDMAPS="var/lib/texmf/arch/installedpkgs/$PKGNAME.maps"
  fi
  if [ -f $OLDMAPS ] ; then
    # temporarily saving old maps file
    cp "$OLDMAPS" "$OLDMAPSSAVE"
  else
    echo "Warning: file $OLDMAPS not found" 
    SYNCWITHTREES="--syncwithtrees"
  fi
}

post_upgrade() {
  echo    ">>> texlive: updating updmap.cfg with new map files..."
  if [ -f "$OLDMAPSSAVE" ] ; then
    MAPSDIFF=`mktemp`
    TOADD=`mktemp`
    diff -B -w $OLDMAPSSAVE $NEWMAPS | sed 's/\s\+/ /g' > $MAPSDIFF
    TOREMOVE=`cat $MAPSDIFF | egrep '^<' | cut -d' ' -f3`
    cat $MAPSDIFF | egrep '^>' | sed 's/^> //' > $TOADD
    if [ "x$TOREMOVE" != "x" ]; then
      for map in $TOREMOVE; do
        sed -i "/\s$map/d" $UPDMAP
      done
    fi
    if [ -s $TOADD ]; then
       cat $TOADD >> $UPDMAP
    fi
  fi
  echo    ">>> texlive: updating the filename database..."
  usr/bin/mktexlsr
  echo    ">>> texlive: updating the fontmap files with updmap..."
  usr/bin/updmap-sys --quiet --nohash $SYNCWITHTREES
  echo    " done." 
  echo    ">>> texlive: recreating all formats..."
  usr/bin/fmtutil-sys --all 1>/dev/null
  echo      " done." 
  echo      " (logs are under /var/lib/texmf/web2c/<engine>/<formatname>.log)"
  echo    "NB: To setup ConTeXt and the lua(la)tex font db,"
  echo    "    see http://wiki.archlinux.org/index.php/TeX_Live"
  if [[ "$2" == 200* ]]; then
    echo      "Important note. Some directories have moved:"
    echo      " \$TEXMFSYSVAR    is now /var/lib/texmf (previously /usr/share/texmf-var)"
    echo      " \$TEXMFSYSCONFIG is now /etc/texmf     (previously /usr/share/texmf-config)"
    echo      "Please move and update the config files you had modified and delete the rest."
    echo      "(Note however that updmap.cfg has been automatically copied and updated.)"
  fi
}

