post_install() {
  cat << EOF
For more info on KDE please have a look at:
'http://wiki.archlinux.org/index.php/KDE'
EOF
 if ! [ `grep '/opt/kde/lib' etc/ld.so.conf` ]; then
    echo "/opt/kde/lib" >>etc/ld.so.conf
    sbin/ldconfig -r .
 fi
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  cat etc/ld.so.conf | grep -v '/opt/kde/lib' >/tmp/.packde
  mv /tmp/.packde etc/ld.so.conf
  chmod 644 etc/ld.so.conf
  sbin/ldconfig -r .
}

op=$1
shift

$op $*
