
post_install() {
  cat << EOM

 --> It is recommended to use qjackctl as a controlling frontend for the
 --> audio server. The extended rights for realtime capabilities can be
 --> granted based on groups or a per user base in
 -->               /etc/security/limits.conf

 --> The audio server comes with a daemon script that runs it as root.
 --> Configuration happens in /etc/conf.d/jack-audio-connection-kit and is
 --> documented there.
 --> NOTE: Running jack as root to enable realtime capabilities isn't
 --> needed any longer.

EOM
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

op=$1
shift

$op $*
