# arg 1: the new package version
post_install() {
	/bin/true
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade() {
	echo "=========================================================="
	echo "| IMPORTANT: Unless you want to run dnsmasq as root, you |"
	echo "|     must either enable CONFIG_SECURITY_CAPABILITIES in |"
	echo "|     your kernel or add capability to the MODULES array |"
	echo "|     in /etc/rc.conf.                                   |" 
	echo "| For more details on configuring dnsmasq, visit:        |"
	echo "|     http://www.thekelleys.org.uk/dnsmasq/doc.html      |"
	echo "=========================================================="
}

# arg 1: the old package version
pre_remove() {
	/bin/true
}

op=$1
shift

$op $*
