#! /bin/sh
case "$*" in
  *-bootclasspath*) ;;
  *)
    if [ ! -f /usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre/lib/rt.jar ]; then
      bcoption="-bootclasspath /usr/share/java/libgcj-4.3.jar"
    fi
esac

case $CLASSPATH in
  */usr/share/java/eclipse-ecj.jar*) ;;
  *) CLASSPATH=${CLASSPATH:+$CLASSPATH:}/usr/share/java/eclipse-ecj.jar
esac
export CLASSPATH

exec /usr/bin/gij \
  org.eclipse.jdt.internal.compiler.batch.Main $bcoption ${1+"$@"}
