post_upgrade() {
	if [ $(vercmp '2.2.8' $2) -ge 0 ]; then
	echo '
	==> New default DocumentRoot

	Apache httpd uses /srv/http as default DocumentRoot.
	You can still use your current DocumentRoot

	==> New default user and group

	Instead of "nobody" apache runs as user/group "http" by default now. You might
	want to adjust your httpd.conf according to this change. But you can still
	run httpd as nobody.
	'
	fi
}