# arg 1:  the new package version
post_install() {
  echo "update desktop and mime database..."
  update-desktop-database
  echo "==> maxima comes with xmaxima  "
  echo "==> if you want to use xmaxima, you must have 'tk' installed!"
  echo "==> ( the commandline maxima will work also without tk )"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
