#!/bin/bash

build() {
    MODULES=" $(checked_modules "drivers/md/*" | grep -v "dm-")"

    # check if a custom mdadm.conf exists
    if grep -qw ^ARRAY "$BASEDIR/etc/mdadm.conf"; then
        echo "Custom /etc/mdadm.conf file will be used in initramfs for assembling arrays."
        add_file "/etc/mdadm.conf"
    fi

    add_binary "mdadm"
    add_file "/lib/udev/rules.d/64-md-raid.rules"
}

help() {
  cat <<HELPEOF
  This hook loads raid arrays with udev.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
