infodir=/usr/share/info
filelist=(nettle.info)

post_install() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    ! [ -f $infodir/$file ] || install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    ! [ -f $infodir/$file ] || install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

# vim:set ts=2 sw=2 et:
