post_install() {
    KERNEL_VERSION='3.1.0-1-ARCH'
    depmod $KERNEL_VERSION
    echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    KERNEL_VERSION='3.1.0-1-ARCH'
    depmod $KERNEL_VERSION
    rmmod nvidia || echo 'In order to use the new nvidia module, exit Xserver and unload it manually.'
}

post_remove() {
    KERNEL_VERSION='3.1.0-1-ARCH'
    depmod $KERNEL_VERSION
}
