#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

[ -f /etc/conf.d/rsyncd ] && . /etc/conf.d/rsyncd

function call_rsyncd() {
	/usr/bin/rsync --daemon $RSYNCD_ARGS
}

case "$1" in
  start)
    stat_busy "Starting rsyncd"
    [ ! -f /var/run/daemons/rsyncd ] && call_rsyncd
    if [ $? -gt 0 ]; then
      stat_fail
    else
      #pgrep -of "/usr/bin/rsync --daemon" > /var/run/rsyncd.pid # Removed FS#20942
      add_daemon rsyncd
      stat_done
    fi
    ;;

  stop)
    stat_busy "Stopping rsyncd"
    [ -f /var/run/rsyncd.pid ] && kill `cat /var/run/rsyncd.pid`
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon rsyncd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
