PKGNAME="texlive-fontsextra"
UPDMAP="/etc/texmf/web2c/updmap.cfg"
SYNCWITHTREES=''
NEWMAPS=`mktemp`
cat <<EOF > $NEWMAPS
Map Acorn.map
Map AnnSton.map
Map ArtNouv.map
Map ArtNouvc.map
Map Carrickc.map
Map Eichenla.map
Map Eileen.map
Map EileenBl.map
Map Elzevier.map
Map GotIn.map
Map GoudyIn.map
Map Kinigcap.map
Map Konanur.map
Map Kramer.map
Map MnSymbol.map
Map MorrisIn.map
Map Nouveaud.map
Map Romantik.map
Map Rothdn.map
Map RoyalIn.map
Map Sanremo.map
Map Starburst.map
Map Typocaps.map
Map Zallman.map
Map antp.map
Map antt.map
Map archaicprw.map
Map arev.map
Map ascii.map
Map augie.map
Map auncial.map
Map aurical.map
Map belleek.map
Map bera.map
Map ccicons.map
Map cm-lgc.map
Map cmin.map
Map cyklop.map
Map dictsym.map
Map dstroke.map
Map epigrafica.map
Map esvect.map
Map fge.map
Map fi4.map
Map foekfont.map
Map fonetika.map
Map fourier-utopia-expert.map
Map fourier.map
Map gfsartemisia.map
Map gfsbodoni.map
Map gfscomplutum.map
Map gfsdidot.map
Map gfsneohellenic.map
Map gfssolomos.map
Map gptimes.map
Map icelandic.map
Map iwona.map
Map kpfonts.map
Map kurier.map
Map libertine.map
Map linearA.map
Map mdbch.map
Map mdput.map
Map mdugm.map
Map pbsi.map
Map phaistos.map
Map recycle.map
Map slantcm.map
Map troff-updmap.map
Map uaq.map
Map ugq.map
Map yfrak.map
Map yly.map
Map yv1.map
Map yv2.map
Map yv3.map
Map yvo.map
Map yvt.map
MixedMap allrunes.map
MixedMap cmll.map
MixedMap hfbright.map
MixedMap lxfonts.map
MixedMap pigpen.map
MixedMap semaf.map
MixedMap trajan.map
EOF

pre_install() {
	cat $NEWMAPS >> $UPDMAP
}

post_install() {
	echo    ">>> texlive: updating the filename database..."
	/usr/bin/mktexlsr
	echo    ">>> texlive: updating the fontmap files with updmap..."
	/usr/bin/updmap-sys --quiet --nohash
	echo    " done." 
}


pre_upgrade() {
  if [[ "$2" == 200* ]]; then
    OLDMAPS="/usr/share/texmf-var/arch/installedpkgs/$PKGNAME.maps"
  else # >= 2010
    OLDMAPS="/var/lib/texmf/arch/installedpkgs/$PKGNAME.maps"
  fi
  if [ -f $OLDMAPS ] ; then
    MAPSDIFF=`mktemp`
    TOADD=`mktemp`
    diff -B $OLDMAPS $NEWMAPS | sed 's/\s\+/ /g' > $MAPSDIFF
    TOREMOVE=`cat $MAPSDIFF | egrep '^<' | cut -d' ' -f3`
    cat $MAPSDIFF | egrep '^>' | sed 's/^> //' > $TOADD
    if [ "x$TOREMOVE" != "x" ]; then
      for map in $TOREMOVE; do
        sed -i "/\s$map/d" $UPDMAP
      done
    fi
    if [ -s $TOADD ]; then
       cat $TOADD >> $UPDMAP
    fi
  else
    echo "Warning: file $OLDMAPS not found" 
    echo "(ignore the above if updating from TL2008 or from TL2009 in testing)"
    SYNCWITHTREES="--syncwithtrees"
  fi
}


post_upgrade() {
	echo    ">>> texlive: updating the filename database..."
	/usr/bin/mktexlsr
	echo    ">>> texlive: updating the fontmap files with updmap..."
	/usr/bin/updmap-sys --quiet --nohash $SYNCWITHTREES
	echo    " done." 
}

pre_remove() {
for m in `cut -d' ' -f2 $NEWMAPS`; do 
  sed -i "/\s$m/d" $UPDMAP ; 
done
}

post_remove() {
  post_install
}
