#!/bin/sh

#set -vx

# At this time, while this script is trivial, we ignore any parameters given.
# However, for backwards compatibility reasons, future versions of this script must 
# support the syntax "update-ca-trust extract" trigger the generation of output 
# files in $DEST.

DEST=/etc/ca-certificates/extracted

# OpenSSL PEM bundle that includes trust flags
# (BEGIN TRUSTED CERTIFICATE)
trust extract --format=openssl-bundle --filter=certificates --overwrite $DEST/openssl/ca-bundle.trust.crt
trust extract --format=pem-bundle --filter=ca-anchors --overwrite --purpose server-auth $DEST/pem/tls-ca-bundle.pem
trust extract --format=pem-bundle --filter=ca-anchors --overwrite --purpose email $DEST/pem/email-ca-bundle.pem
trust extract --format=pem-bundle --filter=ca-anchors --overwrite --purpose code-signing $DEST/pem/objsign-ca-bundle.pem
trust extract --format=java-cacerts --filter=ca-anchors --overwrite --purpose server-auth $DEST/java/cacerts

# Arch uses openssl-directory, too
rm -rf $DEST/openssl/certs
trust extract --format=openssl-directory --filter=certificates $DEST/openssl/certs
ln -srT $DEST/openssl/ca-bundle.trust.crt $DEST/openssl/certs/ca-bundle.trust.crt  
ln -srT $DEST/pem/tls-ca-bundle.pem $DEST/openssl/certs/ca-certificates.crt
ln -srT $DEST/java $DEST/openssl/certs/java
