post_upgrade() {
  if (( $(vercmp $2 1.16.0-3) < 0 )); then
    post_install
  fi
}

post_install() {
  cat <<MSG
>>> xorg-server has now the ability to run without root rights with
    the help of systemd-logind. xserver will fail to run if not launched
    from the same virtual terminal as was used to log in, or with a
    modified xserverrc file.

    Old behavior can be restore through Xorg.wrap config file.
    See Xorg.wrap man page (man xorg.wrap).
MSG
}

