#!/bin/bash

build() {
    add_module btrfs
    add_binary btrfs
    add_runscript
}

help() {
    cat <<HELPEOF
This hook provides support for multi-device btrfs volumes. This hook
is only needed for initramfs images which do not use udev.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
