#!/usr/bin/ash

run_hook() {
    # if udevd is running, this is done async by add/change events
    if [ "$udevd_running" -ne 1 ]; then
        btrfs device scan
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
