# arg 1:  the new package version
post_install() {
  for ver in 5.8.{0,1,2,3,4,5,6,7,8}; do
    [ -h usr/lib/perl5/$ver ] && rm usr/lib/perl5/$ver
    [ -h usr/lib/perl5/site_perl/$ver ] && rm usr/lib/perl5/site_perl/$ver
    [ -h usr/bin/perl$ver ] && rm usr/bin/perl$ver
  done
  return 0
}

post_upgrade() {
  echo '  The directories /usr/lib/perl5/current, /usr/lib/perl5/site_perl/current,'
  echo '  /usr/lib/perl5/site_perl/5.10.1, and /usr/share/perl5/site_perl/5.10.1'
  echo '  will be removed from @INC in a future release.'

  echo '  The directory /usr/bin/perlbin/site will not be added to $PATH in a'
  echo '  future release.'
}
