# Arg 1:  the new package version
post_install() {
  # create kvm group
  systemd-sysusers qemu.conf

  # trigger events on modules files when already loaded
  for _f in /sys/devices/virtual/misc/{kvm,vhost-net}; do
    [[ -e "$_f" ]] &&  udevadm trigger "$_f"
  done
  :
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  if (( "$(vercmp $2 0.11)" < 0 )); then
    echo "With the release of qemu and qemu-kvm 0.12.X, the kqemu kernel module"
    echo "is no longer supported and will be removed from the repositories. You"
    echo "can safely uninstall it from your system."
  fi
  if (( "$(vercmp $2 1.3.1)" < 0 )); then
    echo "With the release of qemu 1.3.0, qemu-kvm binary is removed."
    echo "You need to change the emulator path, if you use libvirt by using:"
    echo "'virsh edit <vm-name>'"
  fi
}
