post_install() {
  # if we have an existing gvim installation - relocate binaries and symlinks
  if [ -f usr/bin/vim ] ; then
    cd usr/bin
    rm -f view rview
    ln -s vim view
    ln -s vim rview
    cd ${OLDPWD}
    echo "Create vim related symlinks..."
  fi
  echo -n "Updating vim help tags..."
  usr/bin/vim --noplugins -u NONE -U NONE \
    --cmd ":helptags usr/share/vim/doc" --cmd ":q" > /dev/null 2>&1
  echo "done."
}

pre_remove() {
  cd usr/bin
  rm -f view rview
  if [ -f usr/bin/vi ] ; then
    ln -s vi view
    ln -s vi rview
    echo "Create vi related symlinks..."
  fi
  cd ${OLDPWD}
}

post_upgrade() {
  post_install $1
}

pre_upgrade() {
  pre_remove $2
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"
