post_common() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_install() {
  post_common

  echo '> Make sure the hddtemp daemon is running, otherwise xfce4-sensors will'
  echo '> crash on start.'
}

post_upgrade() {
  post_common

  if (($(vercmp $2 1.2.3-4) < 0)); then
    echo '> Make sure the hddtemp daemon is running, otherwise xfce4-sensors will'
    echo '> crash on start.'
  fi
}

post_remove() {
  post_common
}

# vim:set ts=2 sw=2 et:
