post_install() {
    printf "==> To enable KSceen, run in a terminal:\n"
    printf "    qdbus org.kde.kded /kded org.kde.kded.unloadModule randrmonitor\n"
    printf "    qdbus org.kde.kded /kded org.kde.kded.setModuleAutoloading randrmonitor false\n"
    printf "    qdbus org.kde.kded /kded org.kde.kded.loadModule kscreen\n"

	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
