post_install() {
	
	cat << EOF 

refind-efi applications have been installed at /usr/lib/refind/*.efi

UEFI FS drivers have deen installed at /usr/lib/refind/drivers_*/

Copy the efi application (according to your UEFI ARCH) 
and /usr/lib/refind/config/refind.conf to a sub-directory of <EFISYS>/EFI/
and add an entry to firmware boot menu using efibootmgr or mactel-boot (for Macs)

rEFInd icons have been installed at /usr/share/refind/icons/

HTML Documentation is available at /usr/share/refind/docs/html/

More info at https://wiki.archlinux.org/index.php/UEFI_Bootloaders#Using_rEFInd

EOF
	
}

post_upgrade() {
	
	post_install
	
}

