post_install() {
  echo "-> Tor has been preconfigured to run as a client only."
  echo "-> Tor is experimental software. Do not rely on it for strong anonymity."
  post_upgrade $1
}

post_upgrade() {
  if [ ! `grep '^tor:' /etc/group` ]; then
    groupadd -g 43 tor &>/dev/null;
  fi

  id tor &>/dev/null || \
    useradd -u 43 -g tor -d /var/lib/tor -s /bin/false tor
}

pre_remove() {
  userdel tor &> /dev/null
  groupdel tor &> /dev/null
}
