# arg 1: the new package version
post_install() {
	post_upgrade
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade() {
	echo ">> IMPORTANT: Unless you want to run pure-ftpd as root, you must"
	echo ">> either enable CONFIG_SECURITY_CAPABILITIES in your kernel"
	echo ">> kernel or add capability to the MODULES array in /etc/rc.conf." 
}

# arg 1: the old package version
pre_remove() {
	/bin/true
}

op=$1
shift

$op $*
