#!/bin/bash

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

PROTOS=(ip ip6 inet arp bridge)

for proto in "${PROTOS[@]}"; do
  nft list tables "$proto"|cut -f 2 -d ' '| while read table; do
    nft flush table "$proto" "$table"
    # Flush removes rules but not chains (contradictory to the man page). Do it manually.
    nft list table "$proto" "$table"|awk '/^[ \t]+chain/{ print $2 }'|while read chain; do
      nft delete chain "$proto" "$table" "$chain"
    done
    nft delete table "$proto" "$table"
  done
done

# vim:set ts=2 sw=2 et:
