--- old/Makefile.in	2012-01-12 00:11:36.000000000 +1100
+++ new/Makefile.in	2012-01-27 11:36:16.110154453 +1100
@@ -130,7 +130,7 @@
 		exit -1 ; \
 	fi
 drill/drill: $(DRILL_LOBJS) $(LIB)
-	$(LINK_EXE) $(DRILL_LOBJS) $(LIBS) -lldns -o drill/drill
+	$(LINK_EXE) $(DRILL_LOBJS) $(LIBS) $(LIBSSL_LIBS) -lldns -o drill/drill
 
 install-drill: drill/drill
 	$(INSTALL) -m 755 -d $(DESTDIR)$(bindir)
@@ -157,7 +157,7 @@
 		exit -1 ; \
 	fi
 $(EXAMPLE_PROGS): $(EXAMPLE_LOBJS) $(LIB)
-	$(LINK_EXE) $@.lo $(LIBS) -lldns -o $@
+	$(LINK_EXE) $@.lo $(LIBS) $(LIBSSL_LIBS) -lldns -o $@
 
 $(TESTNS): $(TESTNS_LOBJS) $(LIB)
 	$(LINK_EXE) $(TESTNS_LOBJS) $(LIBS) -lldns -o $(TESTNS)
