# $Id$
# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Maintainer: Tom K <tomk@runbox.com>

pkgname=perl-mp3-info
_realname=MP3-Info
pkgver=1.23
pkgrel=2
pkgdesc="Manipulate / fetch info from MP3 audio files"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/${_realname}/"
depends=('perl>=5.10.0')
license=('GPL')
source=(http://www.cpan.org/authors/id/D/DA/DANIEL/${_realname}-${pkgver}.tar.gz)
options=(!emptydirs)
md5sums=('fd0b5e0d88ee01454180e3941ab11541')

build() {
  cd  ${startdir}/src/${_realname}-${pkgver}
  # install module in vendor directories.
  /usr/bin/perl Makefile.PL INSTALLDIRS=vendor || return 1
  /usr/bin/make || return 1
  /usr/bin/make DESTDIR=${startdir}/pkg install

  # remove *.pod, .packlist, and empty dirs:
  find ${startdir}/pkg -name perllocal.pod -delete
  find ${startdir}/pkg -name .packlist -delete
}

sha1sums=('692297853bd4d1564a3e9739235a8d851c0b90cb')
