#! /bin/sh
case $CLASSPATH in
  */usr/share/java/eclipse-ecj.jar*) ;;
  *) CLASSPATH=${CLASSPATH:+$CLASSPATH:}/usr/share/java/eclipse-ecj.jar
esac
export CLASSPATH

exec ${JAVA_HOME}/bin/java \
  org.eclipse.jdt.internal.compiler.batch.Main ${1+"$@"}
