pkgname=anjuta

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  update-mime-database usr/share/mime > /dev/null
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  gtk-update-icon-cache -q -t -f usr/share/icons/gnome
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-mime-database usr/share/mime > /dev/null
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  gtk-update-icon-cache -q -t -f usr/share/icons/gnome
  update-desktop-database -q
}
