post_install() {
  if ! [ `grep '/opt/qt/lib' etc/ld.so.conf` ]; then
    echo "/opt/qt/lib" >>etc/ld.so.conf
    sbin/ldconfig -r .
  fi
  echo "INFORMATION:"
  echo "Documentation is seperated it's called qt3-doc"
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  cat etc/ld.so.conf | grep -v '/opt/qt/lib' >/tmp/.pacqt
  mv /tmp/.pacqt etc/ld.so.conf
  chmod 644 etc/ld.so.conf
  sbin/ldconfig -r .
}

op=$1
shift

$op $*
