infodir=/usr/share/info
filelist=(history.info readline.info rluserman.info)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
  echo ">> You can safely ignore any \"cannot open shared object\" errors you see above"
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

