post_install() {
  cat << MSG
  > Please consider supporting Paul Davis, lead developer of Ardour, by
  > either subscribing or at least donating to the project's cause:

      https://community.ardour.org/s/subscribe
      https://community.ardour.org/donate

  > With your continued support, Ardour will continue to improve and will
  > one day no longer be dependent on unstable funding.
MSG
}

# vim:set ts=2 sw=2 et:
