infodir=usr/share/info
filelist=(screen.info screen.info-1 screen.info-2 screen.info-3 screen.info-4 screen.info-5)

post_install() {
    [ -x usr/bin/install-info ] || return 0
    for file in ${filelist[@]}; do
        install-info $infodir/$file.gz $infodir/dir 2> /dev/null
    done
}

post_upgrade() {
    post_install $1
    if [ $(vercmp $2 4.0.3-15) -lt 0 ]; then
        echo 'The location of the screen sockets has changed.'
        echo 'If you need to access running screen sessions, run'
        echo '  # SCREENDIR=/tmp/screens/S-$USER/ screen ...'
    fi
}

pre_remove() {
    [ -x usr/bin/install-info ] || return 0
    for file in ${filelist[@]}; do
        install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
    done
}

