post_install() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
  gconfpkg --install evolution
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  gconfpkg --uninstall evolution
}

post_remove() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}
