scores=(
  'gweled.Normal.scores'
  'gweled.Timed.scores'
)

post_install() {
  for score in "${scores[@]}" ; do
    if [ -e "var/games/${score}" ]; then
      continue
    fi
    touch "var/games/${score}"
    chown root:games "var/games/${score}"
    chmod 664 "var/games/${score}"
  done
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  post_install $1
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
