#!/bin/sh

storepass='changeit'
. /etc/default/cacerts

CLASSPATH=/usr/share/ca-certificates-java
export CLASSPATH

find /etc/ssl/certs -name '*.pem' -printf "+%p\n" | \
	java UpdateCertificates -storepass "${storepass}" >/dev/null
echo "done."
