
# arg 1:  the new package version
post_install() {
  echo "update desktop mime database..."
  update-desktop-database -q /usr/share/applications
  update-mime-database /usr/share/mime 1> /dev/null
}

post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
post_remove() {
  echo "update desktop mime database..."
  update-desktop-database -q
  update-mime-database /usr/share/mime 1> /dev/null
}

op=$1
shift
$op $*
# vim: ft=sh
