#!/bin/sh -e

only_live() {
  if [ ! -d /run/systemd/system ]; then
    echo >&2 "  Skipped: Current root is not booted."
    exit 0
  fi
}

each_conf() {
  while read -r f; do
    "$@" "$(basename "$f")"
  done
}

case $1 in
  catalog)  /usr/bin/journalctl --update-catalog ;;
  hwdb)     /usr/bin/systemd-hwdb --usr update ;;
  update)   touch -c /usr ;;
  sysusers) each_conf /usr/bin/systemd-sysusers ;;
  tmpfiles) each_conf /usr/bin/systemd-tmpfiles --create ;;

  daemon-reload) only_live; /usr/bin/systemctl daemon-reload ;;
  udev-reload)   only_live; /usr/bin/udevadm control --reload ;;
  binfmt)        only_live; each_conf /usr/lib/systemd/systemd-binfmt ;;
  sysctl)        only_live; each_conf /usr/lib/systemd/systemd-sysctl ;;

  *) echo >&2 "  Invalid operation '$1'"; exit 1 ;;
esac

exit 0
