#!/usr/bin/bash

build() {
    local mod
    for mod in dm-mod dm-snapshot dm-mirror; do
        add_module "$mod"
    done

    add_binary "/usr/bin/lvm"
    add_binary "/usr/bin/lvmetad"
    add_binary "/usr/bin/dmsetup"
    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/udev/rules.d/11-dm-lvm.rules"
    add_file "/usr/lib/udev/rules.d/69-dm-lvm-metad.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
    add_file "/etc/lvm/lvm.conf"

    add_file "/usr/lib/systemd/system/lvm2-lvmetad.service"
    add_file "/usr/lib/systemd/system/lvm2-lvmetad.socket"
    add_file "/usr/lib/systemd/system/lvm2-pvscan@.service"
    add_symlink "/usr/lib/systemd/system/sysinit.target.wants/lvm2-lvmetad.socket"
}

help() {
  cat <<HELPEOF
This hook enables LVM2 volumes in systemd-based initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
