# This is a default template for a post-install scriptlet.  You can
# remove any functions you don't need (and this header).

# arg 1:  the new package version
post_install() {
cat << EOF
Note kipi-plugins runtime depends are:
==> k3b,mjpegtools,imagemagick,kdebase,dcraw
EOF
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
