# arg 1:  the new package version
post_install() {
  post_upgrade
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=2.6.24-ARCH
  depmod -a -v $KERNEL_VERSION  > /dev/null 2>&1
}

# arg 1:  the old package version
post_remove() {
  post_upgrade
}

op=$1
shift
$op $*
