post_install() {
	
	cat << EOF 

efilinux has been installed at /usr/lib/efilinux/*.efi

Copy the efi application for your UEFI ARCH to a sub-directory of
<EFISYS>/EFI/ and add an entry to firmware boot menu using efibootmgr
or mactel-boot (for Macs)

Usage instructions at http://thread.gmane.org/gmane.linux.kernel/1172645 
and http://article.gmane.org/gmane.linux.kernel/1175060

EOF
	
}

post_upgrade() {
	
	post_install
	
}

