  # arg 1:  the new package version
post_install() {
cat << EOF
==> To get the HP-Officejet working run as root: ptal-init setup
==> Add ptal-init to /etc/rc.conf daemon list and place it before cups is started!
==> To access scanner enable in /etc/sane.d/dll.conf hpoj line.
==> If you want to use xojpanel please install qt and a X-Server.
EOF

}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
 post_install $1
}

op=$1
shift
$op $*
