## arg 1:  the new package version
post_install() {
  cat << 'EOM'
  
  ==>
  ==> PLEASE NOTE:
  ==> Extended configuration options for NFS (clients & server) are available in
  ==> /etc/conf.d/nfs-common.conf and in /etc/conf.d/nfs-server.conf
  ==>
  ==> Please refer to http://wiki.archlinux.org/index.php/Nfs
  ==> for further information on NFS; for NFSv4, refer to
  ==> http://wiki.archlinux.org/index.php/NFSv4

  ==>  If you plan on using NFSv4, in /etc/conf.d/nfs-common.conf set:
  ==>  1) NEED_IDMAPD="yes" to start rpc.idmapd - on clients & server.
  ==>     rpc.idmapd needs to be properly configured; edit at least the
  ==>     Domain line in /etc/idmapd.conf.
  ==>  2) NEED_GSSD="yes" to start rpc.gssd (GSS authentication) - only on clients.
  ==>  3) Add "rpc_pipefs /var/lib/nfs/rpc_pipefs rpc_pipefs 0 0" to /etc/fstab.
  ==>     If not mounted when the init script nfs-common starts it tries to mount the
  ==>     filesystem automatically (if rpc.idmapd or rpc.gssd is needed);
  ==>     see /etc/conf.d/nfs-common.conf for extended configuration options.

  ==> Only on server /etc/conf.d/nfs-server.conf set:
  ==>  1) add "nfsd /proc/fs/nfsd nfsd -o rw,nodev,noexec,nosuid 0 0" to /etc/fstab.
  ==>     If not mounted when the init script nfs-server starts it tries to mount the
  ==>     filesystem automatically; see /etc/conf.d/nfs-server.conf for extended
  ==>     configuration options.
  ==>  2) NEED_SVCGSSD="yes" to start rpc.svcgssd (GSS authentication) - on server
    
EOM
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  post_install $1
}
