post_install(){
  groupadd -g 492 oprofile &>/dev/null
  useradd -u 492 -g oprofile -s /bin/false oprofile &>/dev/null
}

post_upgrade(){
  getent group oprofile >/dev/null 2>&1 || groupadd -g 492 oprofile &>/dev/null
  getent passwd oprofile >/dev/null 2>&1 || useradd -u 492 -g oprofile -s /bin/false oprofile &>/dev/null
}

post_remove(){
  if getent passwd oprofile >/dev/null 2>&1; then
    userdel oprofile
  fi
  if getent group oprofile >/dev/null 2>&1; then
    groupdel oprofile
  fi
}
