post_install() {
  [[ -f var/lib/dhcp/dhcpd.leases ]] || : >var/lib/dhcp/dhcpd.leases
  [[ -f var/lib/dhcp/dhcpd6.leases ]] || : >var/lib/dhcp/dhcpd6.leases
}

post_upgrade() {
  if (( $(vercmp $2 4.2.4.2) < 0 )); then
    echo ">>> Lease directory moved from /var/state/dhcp"
    echo "    to /var/lib/dhcp. Move your old lease files"
    echo "    if you want to keep using them."
  fi

  post_install
}
