post_install() {
  setcap cap_ipc_lock+ep usr/bin/gnome-keyring-daemon

  # Enable socket by default
  systemctl --global enable gnome-keyring-daemon.socket
}

post_upgrade() {
  setcap cap_ipc_lock+ep usr/bin/gnome-keyring-daemon

  if (( $(vercmp $2 1:42.0-1) < 0)); then
    systemctl --global enable gnome-keyring-daemon.socket
  fi
}

pre_remove() {
  systemctl --global disable gnome-keyring-daemon.socket
}
