pkgname=gnumeric

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  update-desktop-database -q

  echo "==> Install 'python' to enable python plugin support"
  echo "==> Install 'psiconv' for Psion 5 file support"
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-desktop-database -q
}
