post_install() {
    /usr/bin/gtk-query-immodules-3.0 --update-cache
    /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
    /usr/bin/gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

post_upgrade() {
    post_install
}

pre_remove() {
    rm -f /usr/lib/gtk-3.0/3.0.0/immodules.cache
}

post_remove() {
    /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
    /usr/bin/gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}
