--- libspnav-0.2.2/Makefile.in	2010-03-28 00:24:27.000000000 +0100
+++ a/trunk/libspnav/Makefile.in	2014-03-05 15:33:07.590597866 +0100
@@ -4,10 +4,12 @@
 lib_a = libspnav.a
 soname = libspnav.so.0
 lib_so = $(soname).1
+devlink = libspnav.so
 
 CC = gcc
 AR = ar
-CFLAGS = $(opt) $(dbg) -std=c89 -fpic -pedantic -Wall -fno-strict-aliasing -I.
+CFLAGS = $(opt) $(dbg) -std=c89 -fpic -pedantic -Wall -fno-strict-aliasing -I. -I/usr/local/include $(user_cflags)
+LDFLAGS = $(user_ldflags)
 
 .PHONY: all
 all: $(lib_a) $(lib_so)
@@ -16,7 +18,7 @@
 	$(AR) rcs $@ $(obj)
 
 $(lib_so): $(obj)
-	$(CC) -shared -Wl,-soname,$(soname) -o $@ $(obj)
+	$(CC) -shared -Wl,-soname,$(soname) -o $@ $(obj) $(LDFLAGS)
 
 %.o: $(srcdir)/%.c
 	$(CC) $(CFLAGS) -c $< -o $@
@@ -31,13 +33,19 @@
 
 .PHONY: install
 install: $(lib_a) $(lib_so)
-	cp $(lib_a) $(PREFIX)/$(libdir)/$(lib_a)
-	cp $(lib_so) $(PREFIX)/$(libdir)/$(lib_so)
-	for h in $(hdr); do cp -p $(srcdir)/$$h $(PREFIX)/include/; done
+	mkdir -p $(DESTDIR)$(PREFIX)/$(libdir) $(DESTDIR)$(PREFIX)/include
+	cp $(lib_a) $(DESTDIR)$(PREFIX)/$(libdir)/$(lib_a)
+	cp $(lib_so) $(DESTDIR)$(PREFIX)/$(libdir)/$(lib_so)
+	rm -f $(DESTDIR)$(PREFIX)/$(libdir)/$(soname) $(DESTDIR)$(PREFIX)/$(libdir)/$(devlink)
+	ln -s $(PREFIX)/$(libdir)/$(lib_so) $(DESTDIR)$(PREFIX)/$(libdir)/$(soname)
+	ln -s $(PREFIX)/$(libdir)/$(soname) $(DESTDIR)$(PREFIX)/$(libdir)/$(devlink)
+	for h in $(hdr); do cp -p $(srcdir)/$$h $(DESTDIR)$(PREFIX)/include/; done
 
 .PHONY: uninstall
 uninstall:
-	rm -f $(PREFIX)/$(libdir)/$(lib_a)
-	rm -f $(PREFIX)/$(libdir)/$(lib_so)
-	for i in $(hdr); do rm -f $(PREFIX)/include/$$i; done
+	rm -f $(DESTDIR)$(PREFIX)/$(libdir)/$(lib_a)
+	rm -f $(DESTDIR)$(PREFIX)/$(libdir)/$(lib_so)
+	rm -f $(DESTDIR)$(PREFIX)/$(libdir)/$(soname)
+	rm -f $(DESTDIR)$(PREFIX)/$(libdir)/$(devlink)
+	for i in $(hdr); do rm -f $(DESTDIR)$(PREFIX)/include/$$i; done
 
