#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ntpd.conf

case "$1" in
  start)
    stat_busy "Starting NTP Client"
    /usr/bin/ntpd -q $NTP_CLIENT_OPTION &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      add_daemon ntpdate
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping NTP Client"
    rm_daemon ntpdate
    stat_done
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac

