post_upgrade() {
  if (( $(vercmp $2 2.21.15) < 0 )); then
    post_install
  fi
}

post_install() {
  cat <<MSG
>>> This driver now uses SNA as the default acceleration method. You can
    still fall back to UXA if you run into trouble. To do so, save a file
    with the following content as /etc/X11/xorg.conf.d/20-intel.conf :
      Section "Device"
        Identifier  "Intel Graphics"
        Driver      "intel"
        Option      "AccelMethod"  "uxa"
      EndSection
MSG
}

