# this is the scrollkeeper handling sample file

post_install() {
  cat << EOM
  ==> for printing support in cinepaint you will have to install gutenprint
  ==> for support of pythen scripting you will need the python package
EOM
  echo "upgrade desktop mime database ..."
  update-desktop-database -q
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  /bin/true
}

post_remove() {
  echo "upgrade desktop mime database ..."
  update-desktop-database -q
}

op=$1
shift

$op $*
