 # arg 1:  the new package version
post_install() {
cat << EOF
NOTE:
==> There is a good guide to use the ntfsresize utility at:
    'http://mlf.linux.rulez.org/mlf/ezaz/ntfsresize.html'

WARNING:
==> This program "can" cause dataloss if you don't use it right!
==> Make a backup of your files! You have been warned !!!     
EOF

}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
post_install $1
}


op=$1
shift
$op $*