#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ntpd.conf

PIDFILE="/var/run/ntpd/ntpd.pid"
PID=$(cat $PIDFILE 2> /dev/null)

case "$1" in
  start)
    stat_busy "Starting NTP Daemon"
    [ ! -d /var/run/ntpd ] && install -d /var/run/ntpd &>/dev/null
    if [ -z "$PID" ]; then 
       /usr/bin/ntpd $NTPD_ARGS -p /var/run/ntpd/ntpd.pid &>/dev/null
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        add_daemon ntpd
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;
  stop)
    stat_busy "Stopping NTP Daemon"
    if [ -n "$PID" ]; then
      kill $PID &> /dev/null
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        rm $PIDFILE &>/dev/null
        rm_daemon ntpd
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
