#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ntp-client.conf

getPID() {
   echo $(pidof -o %PPID /usr/bin/ntpd);
}

case "$1" in
  start)
    stat_busy "Starting NTP Daemon"
    [ ! -d /var/run/ntpd ] && install -d /var/run/ntpd &>/dev/null
    if [ -z "$(getPID)" ]; then 
       /usr/bin/ntpd $NTPD_ARGS &>/dev/null &
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        echo $(getPID) > /var/run/ntpd/ntpd.pid
        add_daemon ntpd
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;
  stop)
    stat_busy "Stopping NTP Daemon"
    if [ ! -z "$(getPID)" ]; then
      kill $(getPID) &> /dev/null
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        rm -f /var/run/ntpd/ntpd.pid &>/dev/null
        rm_daemon ntpd
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
