## arg 1:  the new package version
post_install() {
cat << 'EOM'
  ==> PLEASE NOTE:
  ==> Extended configuration options for NFS (clients & server) are available in
  ==> /etc/conf.d/nfs-common.conf and in /etc/conf.d/nfs-server.conf
  ==>
  ==> Please refer to http://wiki.archlinux.org/index.php/NFS
  ==> for further information on NFS4; for NFSv3, refer to
  ==> http://wiki.archlinux.org/index.php/NFSv3   
EOM
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  if [ "$(vercmp $2 1.3.0-3)" -lt 0 ]; then
cat << 'EOM'
  ==> IMPORTANT 1.3.0 NFS UTILS CHANGES:
  ==> This is a rather important upgrade, you are going to have to change systemd services files.
  ==> NFS-SERVER:
  ==> systemctl enable nfs-server.service
  ==> NFS-CLIENT:
  ==> systemctl enable nfs-client.target
  ==>
  ==> Extended configuration options for NFS (clients & server) are available in:
  ==> /etc/conf.d/nfs-common
  ==> /etc/conf.d/nfs-server
  ==> Please change them to your needs.
EOM
  fi
}
