# arg 1:  the new package version
post_install() {

  echo -------------------------------
  echo By using this package you accept the NVIDIA license, 
  echo which has been installed in /usr/share/licenses/nvidia-71xx/LICENSE
  echo If you do not accept this license, you must remove the package immediately.
  echo Dont forget to update your /etc/X11/xorg.conf
  echo In order to use nvidia-settings, you need to install 'gtk2' package.
  echo -------------------------------

  ### removing outdated workaround
  if grep 'create-nvidia-nodes.sh' /etc/modprobe.conf >/dev/null 2>&1; then 
     cat /etc/modprobe.conf | grep -v 'create-nvidia-nodes.sh' \
     >/tmp/.pacnvidia
     mv /tmp/.pacnvidia /etc/modprobe.conf
     chmod 644 etc/modprobe.conf
  fi
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
