post_install() {
  if type -P systemd-tmpfiles &> /dev/null; then
    systemd-tmpfiles --create apache.conf
  fi
}

post_upgrade() {
  if type -P systemd-tmpfiles &> /dev/null; then
    systemd-tmpfiles --create apache.conf
  fi

  if [[ $2 == 2\.2\.* ]]; then
    # it is a major upgrade, show a useful link to upgrade instructions
    echo '    Check Apache upgrade instructions: https://httpd.apache.org/docs/2.4/upgrading.html'
  fi
}
