post_install() {
  type -P systemd-tmpfiles >/dev/null && systemd-tmpfiles --create apache.conf
}

post_upgrade() {
  type -P systemd-tmpfiles >/dev/null && systemd-tmpfiles --create apache.conf

  if [[ $2 == 2\.2\.* ]]; then
    # it is a major upgrade, show a useful link to upgrade instructions
    echo '    Check Apache upgrade instructions: https://httpd.apache.org/docs/trunk/upgrading.html'
  fi
}
