# arg 1:  the new package version
post_install() {
  post_upgrade
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  echo "==> ocaml: advanced feature dependences:"
  echo "    -------------------------------------"
  echo "    ncurses: 'ncurses'"
  echo "    tk:      'tk'     "
  echo "        "
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
