post_upgrade() {
  cat << "EOF"
-----------------------------------------------------------
IMPORTANT NOTICE FOR ENCRYPTION USERS

The "password" column in /etc/crypttab has now
two special keywords:
- ASK  ask for a passphrase on boot
- SWAP use a random key and create swapspace
       This is particularly dangerous, as the
       volume in question will be overwritten
       If you use SWAP as your passphrase (which
       is insecure anyway), be sure to remove it
       from /etc/crypttab to avoid dataloss!

See /etc/crypttab(.pacnew) for more information.
-----------------------------------------------------------
Attention netcfg users: netcfg is no longer included as
part of the initscripts package.
Be aware that rc.conf's NET_PROFILES has changed to
NETWORKS, and that netcfg must be installed separately.
For more info, see the netcfg man page.
-----------------------------------------------------------
EOF
}
