pkgname=haskell-http

_register() {
  usr/share/haskell/${pkgname}/register.sh
}

_unregister() {
  usr/share/haskell/${pkgname}/unregister.sh
}

_gen_contents() {
  (cd usr/share/doc/ghc/html/libraries; ./gen_contents_index)
}

post_install() {
  _register
  _gen_contents
}

pre_upgrade() {
  _unregister
}

post_upgrade() {
  _register
  _gen_contents
}

pre_remove() {
  _unregister
}

post_remove() {
  _gen_contents
}
