infodir=usr/share/info
filelist=(cpp-3.3.info cppinternals-3.3.info gcc-3.3.info gccint-3.3.info)

post_install() {
  for file in ${filelist[@]}; do
    install-info ${infodir}/${file}.gz ${infodir}/dir > /dev/null 2>&1
  done
}

post_upgrade() {
  post_install
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete ${infodir}/${file}.gz ${infodir}/dir > /dev/null 2>&1
  done
}
