pre_install() {
  /bin/true
}

post_install() {
  echo "==> Config file is at /etc/slim.conf"
  echo "==> Installed themes in /usr/share/slim/themes"
  echo "==> Add 'slim' to your DAEMONS in /etc/rc.conf"
  echo ""
  echo " If you want to use slim's console command as-is"
  echo "  be sure to install xterm as well"
  /bin/true
}

pre_upgrade() {
  /bin/true
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

op=$1
shift
$op $*
