post_install() {
  echo "updating scrollkeeper catalogue ..."
  scrollkeeper-update -p /var/lib/scrollkeeper > /dev/null 2>&1
  update-desktop-database > /dev/null 2>&1    
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  echo "updating scrollkeeper catalogue ..."
  scrollkeeper-update -p /var/lib/scrollkeeper > /dev/null 2>&1
  update-desktop-database > /dev/null 2>&1      
}

op=$1
shift

$op $*
