post_upgrade() {
	if [ $(vercmp '1.4.19-1' $2) -ge 0 ]; then
	echo '
	==> New default DocumentRoot

	Apache lighttpd uses /srv/http as default DocumentRoot.
	You can still use your current DocumentRoot

	==> New default user and group

	Instead of "nobody" lighttpd runs as user/group "http" by default now. You might
	want to adjust your lighttpd.conf according to this change. But you can still
	run lighttpd as nobody.
	'
	fi
}