
# arg 1:  the new package version
post_install() {
  cat << EOM

--> gimp has built-in cups print support now. for more sophisticated printing,
--> please install gutenprint.

EOM
  echo "update desktop mime database..."
  update-desktop-database -q
}

post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
post_remove() {
  echo "update desktop mime database..."
  update-desktop-database -q
}

op=$1
shift
$op $*
# vim: ft=sh
