post_install() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  post_install $1
  cat << EOM

==> deluge post_upgrade message:

==> After upgrading your Deluge installation, it may fail to start.
==> If this happens to you, you need to remove your ~/.config/deluge directory
==> (make a backup first!) to allow Deluge to rebuild its configuration file.

EOM
}

post_remove() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
