pkgname=rhythmbox

post_install() {
    glib-compile-schemas usr/share/glib-2.0/schemas
    update-desktop-database -q
    gtk-update-icon-cache -f -q -t usr/share/icons/hicolor
}

pre_upgrade() {
     if [ -f usr/share/gconf/schemas/${pkgname}.schemas ]; then
         usr/sbin/gconfpkg --uninstall ${pkgname}
     fi
}

post_upgrade() {
    post_install $1
}


post_remove() {
    post_install $1
}
