diff -Nur module-init-tools-3.4.orig/Makefile.am module-init-tools-3.4/Makefile.am
--- module-init-tools-3.4.orig/Makefile.am	2007-10-07 23:51:46.000000000 +0200
+++ module-init-tools-3.4/Makefile.am	2008-07-22 14:49:09.000000000 +0200
@@ -18,16 +18,9 @@
 EXTRA_depmod_SOURCES = moduleops_core.c
 EXTRA_modinfo_SOURCES = backwards_compat.c
 
-MAN5 = modprobe.conf.5 modules.dep.5 depmod.conf.5
-MAN8 = depmod.8 insmod.8 lsmod.8 rmmod.8 modprobe.8 modinfo.8
-SGML = $(addprefix doc/,  $(MAN5:%.5=%.sgml) $(MAN8:%.8=%.sgml))
-man_MANS = $(MAN5) $(MAN8)
-# If they haven't overridden mandir, fix it (never /man!)
-mandir =$(shell if [ @mandir@ = $(prefix)/man ]; then if [ $(prefix) = / ]; then echo /usr/share/man; else echo $(prefix)/share/man; fi; else echo @mandir@; fi)
-
 TESTSUITE := $(shell find tests -type f ! -name '*~') tests/vg-suppressions
 
-EXTRA_DIST = generate-modprobe.conf modprobe.devfs FAQ CODING stress_modules.sh install-with-care $(SGML) $(man_MANS) $(TESTSUITE)
+EXTRA_DIST = generate-modprobe.conf modprobe.devfs FAQ CODING stress_modules.sh install-with-care $(TESTSUITE)
 
 sbin_PROGRAMS = insmod modprobe rmmod depmod modinfo insmod.static
 bin_PROGRAMS = lsmod
@@ -38,32 +31,6 @@
 
 DIST_DIR := /home/rusty/devel/kernel/www/modules/
 
-MAINTAINERCLEANFILES := $(man_MANS)
-
-# According to Warren Togami, RH has docbook2man in the docbook-utils rpm.
-DOCBOOKTOMAN := $(shell if command -v docbook-to-man >/dev/null 2>&1; then echo docbook-to-man; else echo docbook2man; fi)
-
-# docbook2man writes file itself, doesn't do stdout.
-%.8: doc/%.sgml
-	if [ "$(DOCBOOKTOMAN)" = "docbook2man" ]; then                     \
-	    $(DOCBOOKTOMAN) $< > /dev/null 2>&1;                       \
-	else                                                               \
-	    $(DOCBOOKTOMAN) $< 2>&1 > $@ | sed 's/^[^:]*://';              \
-	fi
-
-%.5: doc/%.sgml
-	if [ "$(DOCBOOKTOMAN)" = "docbook2man" ]; then                     \
-	    $(DOCBOOKTOMAN) $< > /dev/null 2>&1;                       \
-	else                                                               \
-	    $(DOCBOOKTOMAN) $< 2>&1 > $@ | sed 's/^[^:]*://';              \
-	fi
-
-# docbook2man creates extra crap files which need cleaning.
-distclean: killbuildmanpages
-
-killbuildmanpages:
-	rm -f doc/*.tmp manpage.refs manpage.links
-
 tarball: $(DIST_DIR)/module-init-tools-$(VERSION).tar.gz
 
 $(DIST_DIR)/module-init-tools-$(VERSION).tar.gz: dist
