diff -Naur module-init-tools-3.1-orig/Makefile.in module-init-tools-3.1/Makefile.in
--- module-init-tools-3.1-orig/Makefile.in	2004-11-14 16:59:48.000000000 -0800
+++ module-init-tools-3.1/Makefile.in	2004-11-19 11:09:36.000000000 -0800
@@ -704,18 +704,8 @@
 
 # docbook2man writes file itself, doesn't do stdout.
 %.8: doc/%.sgml
-	if [ "$(DOCBOOKTOMAN)" = "docbook2man" ]; then                     \
-	    $(DOCBOOKTOMAN) $< > /dev/null 2>&1;                       \
-	else                                                               \
-	    $(DOCBOOKTOMAN) $< 2>&1 > $@ | sed 's/^[^:]*://';              \
-	fi
 
 %.5: doc/%.sgml
-	if [ "$(DOCBOOKTOMAN)" = "docbook2man" ]; then                     \
-	    $(DOCBOOKTOMAN) $< > /dev/null 2>&1;                       \
-	else                                                               \
-	    $(DOCBOOKTOMAN) $< 2>&1 > $@ | sed 's/^[^:]*://';              \
-	fi
 
 # docbook2man creates extra crap files which need cleaning.
 distclean: killbuildmanpages
