 # arg 1:  the new package version
post_install() {
cat << EOF
==> Please blacklist hisax and misdn modules in /etc/modprobe.d/
EOF
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  EXTRAMODULES=extramodules-3.5-ARCH
  depmod -v $(cat /usr/lib/modules/$EXTRAMODULES/version) > /dev/null 2>&1
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
post_remove() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  EXTRAMODULES=extramodules-3.5-ARCH
  depmod -v $(cat /usr/lib/modules/$EXTRAMODULES/version) > /dev/null 2>&1
}

