post_install() {
	echo
	echo "  > To use FluidSynth as a daemon copy the service file from:"
	echo "      /usr/lib/systemd/system/fluidsynth.service"
	echo "  > to:"
	echo "      /etc/systemd/system/multi-user.target.wants/"
	echo "  > and then edit accordingly."
	echo
	echo "  > PulseAudio output when running as a daemon is known to be"
	echo "  > problematic. See the following bulletin board post:"
	echo "      https://bbs.archlinux.org/viewtopic.php?id=135092"
	echo
}
