#!/bin/sh

storepass='changeit'
. /etc/default/cacerts

JAR=/usr/share/ca-certificates-java/ca-certificates-java.jar

find /etc/ssl/certs -name '*.pem' -printf "+%p\n" | \
  java -Xmx64m -cp $JAR org.debian.security.UpdateCertificates -storepass "$storepass" >/dev/null

if [ $? -eq 0 ]; then
  echo "done."
fi
