#!/bin/bash

build() {
    FILES="/etc/udev/udev.conf"
    SCRIPT="udev"

    add_binary /lib/udev/udevd
    add_binary /usr/bin/udevadm

    for rules in 50-udev-default.rules 60-persistent-storage.rules 80-drivers.rules; do
        add_file "/lib/udev/rules.d/$rules"
    done
    for tool in ata_id scsi_id; do
        add_file "/lib/udev/$tool"
    done
}

help() {
    cat <<HELPEOF
This hook will use udev to create your root device node and detect the needed
modules for your root device. It is also required for firmware loading in
initramfs. It is recommended to use this hook.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
