--- Makefile.old	2010-07-23 04:16:11.000000000 -0300
+++ Makefile	2010-07-23 04:16:11.000000000 -0300
@@ -42,7 +42,7 @@
 	    protocol-numbers.iana port-numbers.iana
 
 protocol-numbers.iana:
-	$(AWK) -f get.gawk -v file=protocol-numbers >protocol-numbers.iana
+	$(AWK) -f get.gawk -v file=protocol-numbers/protocol-numbers.txt >protocol-numbers.iana
 	rm -f protocol-numbers
 
 port-numbers.iana:
