#!/bin/sh

#set -vx

# At this time, while this script is trivial, we ignore any parameters given.
# However, for backwards compatibility reasons, future versions of this script must 
# support the syntax "update-ca-trust extract" trigger the generation of output 
# files in $DEST.

DEST=/etc/ca-certificates/extracted
SSL=/etc/ssl/certs

trust extract --overwrite --format=pem-bundle --filter=ca-anchors --purpose server-auth  $DEST/tls-ca-bundle.pem
trust extract --overwrite --format=pem-bundle --filter=ca-anchors --purpose email        $DEST/email-ca-bundle.pem
trust extract --overwrite --format=pem-bundle --filter=ca-anchors --purpose code-signing $DEST/objsign-ca-bundle.pem

# Removes all files in /etc/ssl/certs, but not directories or files therein
trust extract --overwrite --format=openssl-directory --filter=certificates $SSL

# 'trust extract' makes everything it generated mode 0555; let's not do that for the directory
chmod 0755 $SSL

trust extract --overwrite --format=openssl-bundle --filter=certificates $SSL/ca-bundle.trust.crt
trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose server-auth $SSL/java/cacerts
ln -fsrT $DEST/tls-ca-bundle.pem $SSL/ca-certificates.crt
