post_install() {
  EXTRAMODULES='extramodules-2.6.32-lts'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)  
  echo "if you are running kms in early mode please rebuild your initrd"
}

post_upgrade() {
  post_install $1
  rmmod nouveau || echo 'In order to use the new nouveau module, exit Xserver and unload it manually.'
}

post_remove() {
  EXTRAMODULES='extramodules-2.6.32-lts'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

