post_install () {
  # Check user/group munin exists
  getent group munin >/dev/null || groupadd --system munin
  getent passwd munin >/dev/null || useradd --system -c "Munin system monitor" -g munin -s /bin/false -d /var/lib/munin munin
  # Fix permissions
  chown munin.munin -R /var/log/munin /var/lib/munin /var/run/munin
  # Do basic configuration
  echo "==> Run the following to get a good set of default plugins:"
  echo "    /usr/sbin/munin-node-configure --shell | sh"
}
