post_install () {
  # Display cron command
  echo "See the example cron entry (for the munin user) for further setup:
    /etc/munin/munin-cron-entry"
  post_upgrade
}

post_upgrade() {
  # Ensure directories exist
  mkdir -p /var/{lib,log}/munin /run/munin
  # Fix permissions on necessary directories
  chown munin.munin /var/{lib,log}/munin /run/munin
  chown munin.munin /var/lib/munin/spool
  fc-cache /usr/lib/munin
}

post_remove() {
  fc-cache /usr/lib/munin
}
