#!/bin/sh

storepass='changeit'
. /etc/default/cacerts

find /etc/ssl/certs -name '*.pem' -printf "+%p\n" | \
  java \
    -cp /usr/share/ca-certificates-java/ca-certificates-java.jar \
    org.debian.security.UpdateCertificates \
    -storepass "$storepass" \
    >/dev/null
