#!/bin/sh

storepass='changeit'
. /etc/default/cacerts

JAR=/usr/share/ca-certificates-java/ca-certificates-java.jar

find /etc/ssl/certs -name '*.pem' -printf "+%p\n" | \
	java -jar $JAR -storepass "$storepass" >/dev/null
echo "done."
