# this is the scrollkeeper handling sample file

post_install() {
  cat << EOF

NOTE on dvdrip
----
 ==> in order to create ogm/odd video files, you will need ogmtools
 ==> pacman -S ogmtools

EOF
  echo "update desktop mime database..."
  update-desktop-database -q
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  /bin/true
}

post_remove() {
  echo "update desktop mime database..."
  update-desktop-database -q
}

op=$1
shift

$op $*
