#!/bin/bash

# source application-specific settings
[ -f /etc/conf.d/metalog ] && . /etc/conf.d/metalog

. /etc/rc.conf
. /etc/rc.d/functions

if [ -f /var/run/metalog.pid ]; then
    PID=$(cat /var/run/metalog.pid) 2>/dev/null
fi

case "$1" in
  start)
    stat_busy "Starting Metalog"
    [ -z "$PID" ] && /usr/sbin/metalog -B $METALOG_OPTS 2>&1
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon metalog
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Metalog"
    [ ! -z "$PID" ]  && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon metalog
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}" 
esac
exit 0 
