post_install () {
     getent group brlapi  &>/dev/null || groupadd -r brlapi
     if [ ! -e /etc/brlapi.key ]; then
         mcookie >/etc/brlapi.key
         chmod 0640 /etc/brlapi.key
         chgrp brlapi /etc/brlapi.key
         echo "Please add your user to the brlapi group."
     fi
}

post_upgrade () {
    post_install
}

post_remove () {
    getent group brlapi >/dev/null 2>&1 && groupdel brlapi
    if [ -e /etc/brlapi.key ]; then
        rm -f /etc/brlapi.key
    fi
}
