pre_install() {
	/bin/true
}

post_install() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=2.6.26-ARCH
  depmod -v $KERNEL_VERSION > /dev/null 2>&1
  /bin/true
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=2.6.26-ARCH
  depmod -v $KERNEL_VERSION > /dev/null 2>&1
  /bin/true
}

post_remove() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=2.6.26-ARCH
  depmod -v $KERNEL_VERSION > /dev/null 2>&1
  /bin/true
}

op=$1
shift
$op $*
