post_install() {
  if ! getent group memcached >/dev/null; then
    groupadd --system memcached
  fi
  if ! getent passwd memcached >/dev/null; then
    useradd --system -c 'memcached user' -g memcached -d / -s /bin/bash memcached
  fi
}

post_upgrade() {
  post_install $1
}

post_remove() {
  if getent passwd memcached >/dev/null; then
    userdel memcached
  fi
  if getent group memcached >/dev/null; then
    groupdel memcached
  fi
}
