# arg 1:  the new package version
post_install() {
	# we need to ldconfig first, in case xfree86's libs aren't
	# in ld.so.cache yet
	sbin/ldconfig -r .
	mkdir -p etc/gtk-2.0 &>/dev/null
	usr/bin/gtk-query-immodules-2.0 >etc/gtk-2.0/gtk.immodules
	usr/bin/gdk-pixbuf-query-loaders >etc/gtk-2.0/gdk-pixbuf.loaders
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	post_install $1
}

# arg 1:  the old package version
pre_remove() {
	rm -f etc/gtk-2.0/gtk.immodules &>/dev/null
	rm -f etc/gtk-2.0/gdk-pixbuf.loaders &>/dev/null
	rmdir etc/gtk-2.0 &>/dev/null
}

op=$1
shift

$op $*
