_scores=(
	gnome-nibbles.1.0.scores
	gnome-nibbles.2.0.scores
	gnome-nibbles.3.0.scores
	gnome-nibbles.4.0.scores
	gnome-nibbles.1.1.scores
	gnome-nibbles.2.1.scores
	gnome-nibbles.3.1.scores
	gnome-nibbles.4.1.scores
)

post_install() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  update-desktop-database -q
  gtk-update-icon-cache -q -f usr/share/icons/hicolor

  for score in "${_scores[@]}" ; do
    if [ -e "var/games/$score" ]; then
      continue
    fi

    touch "var/games/$score"
    chown root:games "var/games/$score"
    chmod 664 "var/games/$score"
  done
}

post_upgrade() {
  post_install
}

post_remove() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  update-desktop-database -q
  gtk-update-icon-cache -q -f usr/share/icons/hicolor

  for score in "${_scores[@]}" ; do
    rm -f "var/games/$score"
  done
}
