show_efi_msg() {
  cat << EOF

==> For setting up Syslinux EFI follow
    https://wiki.archlinux.org/index.php/Syslinux#UEFI_Systems

==> The syslinux-install_update script does not currently support EFI install

EOF
}

show_bios_autoupdate_msg() {
  cat << EOF

==> For setting up Syslinux BIOS using the syslinux-install_update script follow
    https://wiki.archlinux.org/index.php/Syslinux#Automatic_Install
EOF
}

post_install() {
  [ -f /boot/syslinux/SYSLINUX_AUTOUPDATE ] || show_bios_autoupdate_msg
  [ -d /sys/firmware/efi ] && show_efi_msg

  true
}

post_upgrade() {
  ## auto-update syslinux if /boot/syslinux/SYSLINUX_AUTOUPDATE exists
  /usr/bin/syslinux-install_update -s

  post_install
}
