# arg 1:  the new package version
post_install() {
  /usr/bin/update-mime-database /usr/share/mime
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /usr/bin/update-mime-database /usr/share/mime
}

# arg 1:  the old package version
pre_remove() {
  /usr/bin/update-mime-database /usr/share/mime
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
