#!/bin/sh
# 
# A small wrapper script for launching both
# giftd & giFTcurs.
#
# Initially written (I guess :) by Sarah Hay
# Modified (20040112) by Manolis Tzanidakis
#

# check if giftd is already running & stop it.
if pidof giftd &>/dev/null; then
  echo "You've got giFTd running. Would you like to"
  echo -n "restart it before running giFTcurs ? y/[n]: "
  read YN
  if test ! $YN; then YN="n"; fi
  if test $YN = "y"; then
    echo "Restarting giFT daemon..."
    killall -TERM giftd
    sleep 1
    /usr/bin/giftd -d
  fi
else
  /usr/bin/giftd -d
fi

# wait for giFTd to initialize 
# before starting giFTcurs
sleep 1

# start giFTcurs
/usr/bin/giFTcurs

# keep running giftd or stop it ?
echo -n "Do you want to stop giFTd? y/[n]: "
read YN
if test ! $YN; then YN="n"; fi
if test $YN != "y"; then
  echo "giFTd is running as process `pidof giftd`. Enjoy :)"
  exit 0
else
  if killall -TERM giftd; then 
    echo "giFTd stopped."
  else
    echo "Stopping giFTd failed, pls stop it manually."
  fi
fi
