post_install() {
  if ! getent passwd deluge &>/dev/null; then
    groupadd -g 125 deluge
    useradd -c 'Deluge user' -u 125 -g deluge -d /srv/deluge -s /bin/false deluge
    passwd -l deluge &>/dev/null
  fi

  post_upgrade
}

post_upgrade() {
  [[ -x /usr/bin/xdg-icon-resource ]] && xdg-icon-resource forceupdate --theme hicolor
  [[ -x /usr/bin/update-desktop-database ]] && update-desktop-database -q
  return 0
}

post_remove() {
  post_upgrade
}
