#!/bin/sh

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  if (( "$(vercmp "$2" 0.19.20121005)" < 0 )); then
    echo 'btrfs multi-device support now relies on linux 3.6 or later'
  elif (( "$(vercmp "$2" 4.3.1-2)" < 0 )); then
    echo 'btrfs-scrub@.timer instance names must not be prefix by dash anymore'
    echo 'use btrfs-scrub@-.timer to scrub / monthly'
    echo '    btrfs-scrub@home.timer to scrub /home monthly.'
  fi
}

# vim:set ts=2 sw=2 et:
