#!/bin/bash

build() {
    MODULES=$(all_modules btrfs)
    BINARIES=btrfs
    SCRIPT=btrfs
}

help() {
    cat <<HELPEOF
This hook provides support for multi-device btrfs volumes.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
