post_upgrade() {
	echo "=> This version doesn't include  PIL, libxml2 and elementtree bindings for python24 (required by plone 3)"
	echo "=> You can get these packages from my private repository: http://archlinux.hoetzel.info/juergen/os/i686/"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_install() {
	/bin/true
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
