# $Id$
# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Maintainer: Tom K <tomk@runbox.com>

pkgname=perl-yaml-syck
_realname=YAML-Syck
pkgver=1.00
pkgrel=1
pkgdesc="Fast, lightweight YAML loader and dumper "
arch=('i686' 'x86_64')
license=('custom')
url="http://search.cpan.org/dist/${_realname}/"
depends=('perl>=5.10.0')
options=('!emptydirs')
source=(http://www.cpan.org/authors/id/A/AU/AUDREYT/${_realname}-$pkgver.tar.gz)
md5sums=('1bf501c3d3df4763bbd2f134d51f0a3f')

build() {
  cd  $startdir/src/${_realname}-$pkgver
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${startdir}/pkg || return 1

  # remove perllocal.pod and .packlist
  find ${startdir}/pkg -name perllocal.pod -delete
  find ${startdir}/pkg -name .packlist -delete

  mkdir -p ${startdir}/pkg/usr/share/licenses/${pkgname}
  install -m644 COPYING ${startdir}/pkg/usr/share/licenses/${pkgname}/
}
