#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting HTTP Daemon"
      /usr/sbin/apachectl start &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon httpd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping HTTP Daemon"
    /usr/sbin/apachectl stop &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon httpd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  reload)
    if [ -f /var/run/httpd/httpd.pid ]; then
      status "Reloading HTTP Configuration" kill -HUP `cat /var/run/httpd/httpd.pid`
    fi
    ;;
  *)
    echo "usage: $0 {start|stop|restart|reload}"
esac
