#!/bin/sh

post_upgrade() {
  # return if old package version greater 3.1.2-5...
  (( $(vercmp "$2" '3.1.2-5') > 0 )) && return

  # return if neither service nor socket is enabled...
  systemctl -q is-enabled rsyncd.service rsyncd.socket || return

  echo ' > For security reasons the rsyncd service protects home (/root and /home are'
  echo ' > inaccessibly) and system (/boot, /etc and /usr are read-only). If you need'
  echo ' > access use rsync via ssh or see the wiki for instructions to override:'
  echo ' > https://wiki.archlinux.org/index.php/Rsync#rsync_daemon'
}
