post_install() {
    gtk-query-immodules-2.0 > etc/gtk-2.0/gtk.immodules
    gtk-query-immodules-3.0 --update-cache 

    gtk-update-icon-cache -fq -t usr/share/icons/hicolor

    glib-compile-schemas /usr/share/glib-2.0/schemas
}

post_remove() {
    gtk-query-immodules-2.0 > etc/gtk-2.0/gtk.immodules
    gtk-query-immodules-3.0 --update-cache 

    gtk-update-icon-cache -fq -t usr/share/icons/hicolor

    glib-compile-schemas /usr/share/glib-2.0/schemas
}
