#!/bin/bash


pkgver=4.4
pkgrel=3


. /etc/makepkg.conf

if [ -r ~/.makepkg.conf ]; then
	. ~/.makepkg.conf
fi

pkgname=('kdeaccessibility'
         'kdeadmin'
         'kdeartwork'
         'kdebase'
         'kdeedu'
         'kdegames'
         'kdegraphics'
         'kdemultimedia'
         'kdenetwork'
         'kdepim'
         'kdeplasma-addons'
         'kdesdk'
         'kdetoys'
         'kdeutils'
         'kdewebdev')

pkgname=($(echo ${pkgname[@]} | sort -u))

echo     '# $Id: $'
echo -e  '# Maintainer: Pierre Schmitz <pierre@archlinux.de>\n'
echo     'pkgbase=kde-meta'
echo -en 'pkgname=('
ct=0
for k in ${pkgname[@]}; do
	[ $ct -gt 0 ] && echo -en "\n         "
	echo -n "'kde-meta-${k}'"
	ct=$(($ct+1))
done
echo    ')'
echo     "pkgver=${pkgver}"
echo     "pkgrel=${pkgrel}"
echo     "arch=('any')"
echo     "url='http://www.archlinux.org/'"
echo     "license=('GPL')"
echo -e  "groups=('kde-meta')\n"
echo     'build() {'
echo     '	return 0'
echo -e  '}\n'

for i in ${pkgname[@]}; do 
	echo     "package_kde-meta-${i}() {"
	echo -e  "\tpkgdesc=('Meta package for ${i}')"
	echo -en '\tdepends=('
	ct=0
	for j in $(pacman -Qgq ${i} | sort -u); do
		[ $ct -gt 0 ] && echo -en "\n\t         "
		echo -n "'${j}'"
		ct=$(($ct+1))
	done
	echo     ')'
	echo -e  "\treplaces=('${i}')"
	echo -e  "\tconflicts=('${i}')"
	echo -e  "}\n"
done
