#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/gpsd ] && . /etc/conf.d/gpsd

NAME=gpsd
DAEMON=/usr/sbin/gpsd
PIDFILE=/run/gpsd.pid
PID=$(cat $PIDFILE 2>/dev/null)

case "$1" in
   start)
	stat_busy "Starting gpsd"
	[ -z "$PID" ] && "$DAEMON" -P $PIDFILE -F /run/gpsd.sock ${GPSD_OPTIONS} ${DEVICES}
	if [ $? -gt 0 ]; then
		stat_fail
	else
		add_daemon $NAME
		stat_done
	fi
   ;;
   stop)
	stat_busy "Stopping $NAME"
	[ ! -z "$PID" ]  && kill $PID &> /dev/null
	if [ $? -gt 0 ]; then
		stat_fail
	else
	    rm -f $PIDFILE &>/dev/null
	    rm_daemon $NAME
	    stat_done
	fi
   ;;

   restart)
	$0 stop
	sleep 2
	$0 start
   ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
