post_install() {
  # create user for uuidd
  if ! getent group uuidd >/dev/null; then
    groupadd -r uuidd
  fi

  if ! getent passwd uuidd >/dev/null; then
    useradd -r -s /sbin/nologin -g uuidd uuidd
  fi

  # ensure /run/uuidd exists
  systemd-tmpfiles --create uuidd.conf
}

post_upgrade() {
  if [ "$(vercmp $2 2.21.2-4)" -lt 0 ]; then
    if [ -f /var/lib/hwclock/adjtime ]; then
      mv /var/lib/hwclock/adjtime /etc/adjtime
    fi
    if [ -d /var/lib/hwclock ]; then
      rmdir /var/lib/hwclock
    fi
  fi

  post_install
}

post_remove() {
  if getent passwd uuidd >/dev/null; then
    userdel uuidd
  fi

  if getent group uuidd >/dev/null; then
    userdel uuidd
  fi
}
