post_install() {
  post_upgrade
}

post_upgrade() {
  if [ -d usr/share/kobo-deluxe/kobo-deluxe/scores ] ; then
    mkdir -p var/games/kobo-deluxe/scores/
    for i in usr/share/kobo-deluxe/kobo-deluxe/scores/* ; do
      mv $i var/games/kobo-deluxe/scores/
    done
    rmdir usr/share/kobo-deluxe/kobo-deluxe/scores
    rmdir usr/share/kobo-deluxe/kobo-deluxe
    chgrp -R games var/games/kobo-deluxe/scores/
  fi
}
