post_install() {
  update-desktop-database -q
  
  echo "For correct setup please take a look at the wiki:"
  echo "http://wiki.archlinux.org/index.php/FreeNX"
  
  
}

post_upgrade() {
  update-desktop-database -q
  
  if [ "`vercmp $2 3.5.0.7-1.1`" -lt 0 ]; then
    # important upgrade notice
    echo "because file location of the default key has been moved"
    echo "you may need to reconfigure your connection and settings"
  fi
}

post_remove() {
  update-desktop-database -q
}
