# remove localstatedir -- compiled VCL and slab files will still be here.
post_remove() {
  rm -rf var/lib/varnish
}

post_upgrade() {
  if [[ $(vercmp 5.0.0-1 "$2") -eq 1 ]]; then
    echo ":: You must update your VCL to be compatible with varnish 5.0.0. See the"
    echo "   following upgrade guide to port your configuration:"
    echo "   http://varnish-cache.org/docs/5.0/whats-new/upgrading-5.0.html"
  fi
}
