post_install() {
  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  usr/sbin/gconfpkg --install aisleriot
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall aisleriot
}

post_remove() {
  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -f -t usr/share/icons/hicolor
}
