infodir=/usr/share/info
filelist=(as.info bfd.info binutils.info configure.info gprof.info ld.info standards.info)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

# vim:set ts=2 sw=2 et:
