post_install() {
	if [ -z "`grep '^http::' /etc/group`" ]; then
		groupadd -g 33 http >& /dev/null
	fi
	if [ -z "`grep '^http:' /etc/passwd`" ]; then
		useradd -u 33 -d /srv/http -g http -s /bin/false http &>/dev/null
	fi
}

post_upgrade() {
	post_install

	if [ $(vercmp '2.2.8' $2) -ge 0 ]; then
	echo '
	==> New default DocumentRoot

	Apache httpd uses /srv/http as default DocumentRoot.
	You can still use your current DocumentRoot

	==> New default user and group

	Instead of "nobody" apache runs as user/group "http" by default now. You might
	want to adjust your httpd.conf according to this change. But you can still
	run httpd as nobody.
	'
	fi
}

pre_remove() {
	userdel http &> /dev/null
	groupdel http &> /dev/null
}