post_install() {
	echo '
	==> Optional modules and their requirements

	* mod_webdav		: libxml2, sqlite3, e2fsprogs
	* mod_cml		: lua
	* mod_magnet		: lua
	* mod_trigger_b4_dl	: gdbm
	* mod_mysql_vhost	: libmysqlclient

	'
}

post_upgrade() {
	post_install

	if [ $(vercmp '1.4.19-1' $2) -ge 0 ]; then
	echo '
	==> New default DocumentRoot

	lighttpd uses /srv/http as default DocumentRoot.
	You can still use your current DocumentRoot

	==> New default user and group

	Instead of "nobody" lighttpd runs as user/group "http" by default now. You might
	want to adjust your lighttpd.conf according to this change. But you can still
	run lighttpd as nobody.
	'
	fi
}
