

post_install() {
  cat << 'EOM'
  
  ==>
  ==> PLEASE NOTE:
  ==> Extended configuration options for NFS are available in
  ==> /etc/conf.d/nfs.
  ==>
  ==> Please refer to http://wiki.archlinux.org/index.php/Nfs
  ==> for further information.
  ==>

EOM
}

post_upgrade() {
  cat << 'EOM'
  
  ==>
  ==> PLEASE NOTE:
  ==> Extended configuration options for NFS are now available in
  ==> /etc/conf.d/nfs.
  ==> If /etc/conf.d/nfsd remains on your system from an earlier
  ==> installation, transfer its settings to /etc/conf.d/nfs and
  ==> delete it.
  ==>
  ==> Please refer to http://wiki.archlinux.org/index.php/Nfs
  ==> for further information.
  ==>

EOM
}
      
op=$1
shift
$op $*
