# arg 1:  the new package version
post_install() {
  KERNEL_VERSION='2.6.25-ARCH'
  depmod -v $KERNEL_VERSION  > /dev/null 2>&1		 
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
  rmmod nvidia || echo 'In order to use the new nvidia module, exit Xserver and unload it manually.'
}

# arg 1:  the old package version
post_remove() {
  KERNEL_VERSION='2.6.25-ARCH'
  depmod -v $KERNEL_VERSION	 > /dev/null 2>&1	 
}

op=$1
shift
$op $*
