post_install() {
  cat << MES
>>> See the wiki at http://wiki.archlinux.org/index.php/PulseAudio for details
    on configuring your system for PulseAudio.

>>> Make sure to install pulseaudio-alsa to configure ALSA for PulseAudio.
MES
}

post_upgrade() {
  cat << MES
>>> If you have per-user copies of configuration files (such as client.conf,
    daemon.conf or default.pa) in ~/.pulse/, make sure you keep them in sync
    with changes to the packaged files in /etc/pulse/. Otherwise, PulseAudio
    may refuse to start due to configuration errors.
MES
}

# vim:set ts=2 sw=2 et:
