#! /bin/sh

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/gpsd ] && . /etc/conf.d/gpsd

NAME=gpsd
DAEMON=/usr/sbin/$NAME
PID=$(pidof -o %PPID /usr/sbin/gpsd)

case "$1" in
   start)
	stat_busy "Starting gpsd"
	[ ! -d /var/run/gpsd ] && install -d /var/run/gpsd
	[ -z "$PID" ] && "$DAEMON" ${GPSD_OPTIONS} -F ${GPSD_SOCKET} ${DEVICES}
	if [ $? -gt 0 ]; then
		stat_fail
	else
		add_daemon gpsd
		stat_done
	fi
   ;;
   stop)
	stat_busy "Stopping gpsd"
	[ ! -z "$PID" ]  && kill $PID &> /dev/null
	if [ $? -gt 0 ]; then
		stat_fail
	else
	rm -f /var/run/$PID.pid &>/dev/null
	rm_daemon gpsd
	stat_done
	fi
   ;;

   restart)
	$0 stop
	sleep 2
	$0 start
   ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
