
print_install() {
  printf "\n"
  echo "Run faxsetup to configure and be sure to set..."
  echo "  The device to configure is usually ttyS0"
  echo "  The number of pages to accept to more than 25"
  echo "  The country code and area code"
  echo "  The faxclass to 2.0"
  echo "  Most other defaults are OK"
  printf "\n"
}

print_remove() {
  printf "\n\n"
  echo "You may manually remove /var/spool/hylafax and /usr/lib/fax if you do not need anything."
  echo "You may also remove any aliases added to /etc/mail/aliases."
  printf "\n"
}

post_install() {
  post_upgrade
  print_install
}

post_upgrade() {
  groupadd -g 14 uucp &>/dev/null
  useradd -u 10 -g uucp -d '/' -s /bin/false uucp &>/dev/null
  useradd -u 69 -g daemon -d '/' -s /bin/false fax &>/dev/null
  chown uucp /var/spool/hylafax/{,archive,bin,client,config,dev,docq,doneq,etc}
  chown uucp /var/spool/hylafax/{FIFO,info,log,pollq,recvq,sendq,status,tmp}
  chown uucp /var/spool/hylafax/etc/{hosts.hfaxd,lutRS18.pcf,xferfaxlog}
  chown -R uucp /var/spool/hylafax/etc/templates
  usermod -d '/' uucp &>/dev/null
  usermod -d '/' fax &>/dev/null
}

pre_remove() {
  userdel uucp &>/dev/null
  groupdel uucp &>/dev/null
  userdel fax &>/dev/null
  print_remove
}
