# arg 1:  the new package version
post_install() {
  echo "octave: install 'texinfo' for help-support in octave"
  echo "octave: install 'gnuplot' to be able to plot in octave"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  echo "octave: install 'texinfo' for help-support in octave"
  echo "octave: install 'gnuplot' to be able to plot in octave"
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
