pkgname=bug-buddy

post_install() {
    usr/bin/gtk-query-immodules-2.0 > etc/gtk-2.0/gtk.immodules
    usr/sbin/gconfpkg --install ${pkgname}
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

pre_upgrade() {
    pre_remove $1
}

post_upgrade() {
    post_install $1
}

pre_remove() {
    usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
    usr/bin/gtk-query-immodules-2.0 > etc/gtk-2.0/gtk.immodules
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
