post_install() {
  cat << _EOF
    Quod Libet comes with a limited set of dependencies.
    By default, Quod Libet comes with MP3 and OGG Vorbis support.
    To enable extra features, take a look at:

        http://www.sacredchao.net/quodlibet/wiki/Guide/Requirements

    Most of these are available as a package from the repositories
_EOF
}

post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
