#!/bin/bash

build() {
    local mod
    for mod in dm-mod dm-snapshot dm-mirror; do
        add_module "$mod"
    done

    add_binary "/sbin/lvm"
    add_binary "/sbin/lvmetad"
    add_binary "/sbin/dmsetup"
    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/udev/rules.d/11-dm-lvm.rules"
    add_file "/usr/lib/udev/rules.d/69-dm-lvm-metad.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
    add_file "/etc/lvm/lvm.conf"

    add_runscript
}

help() {
  cat <<HELPEOF
This hook enables LVM2 volumes in initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
