#!/bin/bash

build() {
    add_module btrfs
    add_binary btrfs
    add_runscript
}

help() {
    cat <<HELPEOF
This hook provides support for multi-device btrfs volumes, in the absence of udev.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
