post_install() {
  if [ ! -e /usr/share/games/pathological/pathological_scores ]; then
    cat << _EOF > /usr/share/games/pathological/pathological_scores
0 all-boards 1 John-Paul
0 all-boards 1 Kim
0 all-boards 1 Matths
0 all-boards 1 Carrie
0 all-boards 1 Mike
0 all-boards 1 Dale
0 all-boards 1 Alesh
0 all-boards 1 Thanks to
0 all-boards 1 everyone who
0 all-boards 1 contributed!
_EOF
  chown root:users /usr/share/games/pathological/pathological_scores
  chmod 664 /usr/share/games/pathological/pathological_scores
  fi
}

post_upgrade() {
  post_install $1
}

post_remove() {
  rm -f /usr/share/games/pathological/pathological_scores
}

op=$1
shift

$op $*
