#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /sbin/portmap`
case "$1" in
  start)
    stat_busy "Starting Portmap"
    [ -z "$PID" ] && /sbin/portmap
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/portmap.pid
      add_daemon portmap
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Portmap"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/portmap.pid
      rm_daemon portmap
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
