_infodir=/usr/share/info
_filelist=(check.info)

post_install() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${_filelist[@]}; do
    install-info $_infodir/$file $_infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${_filelist[@]}; do
    install-info --delete $_infodir/$file $_infodir/dir 2> /dev/null
  done
}
