post_install() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

post_upgrade() {
  post_install
  if [[ $(vercmp 3.18.0-2 "$2") -eq 1 ]]; then
    echo "The SSH_ASKPASS environment variable is not exported by default anymore. Set it in /etc/profile to revert to the previous behavior"
  fi
}

post_remove() {
  post_install
}
