#!/bin/bash

build() {
    FILES="/etc/pcmcia/config.opts"
    MODULES=" $(checked_modules '/drivers/pcmcia/' | grep -ve 'sound' -e 'net') $(checked_modules '/ide/legacy')"

    [[ $MODULES ]] && MODULES+=" sd_mod?"

    add_binary "/usr/lib/udev/pcmcia-socket-startup"
    add_binary "/usr/lib/udev/pcmcia-check-broken-cis"
    add_file "/usr/lib/udev/rules.d/60-pcmcia.rules"
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for a pcmcia root device.  Detection will
take place at runtime. To minimize the modules in the image, add the autodetect
hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
