#!/bin/bash

 . /etc/rc.conf
 . /etc/rc.d/functions

 case "$1" in

   start)
     stat_busy "Starting LISa"
     /opt/kde/bin/lisa &>/dev/null
     if [ $? -ne 0 ]; then
       stat_fail
     else
       add_daemon lisa
       stat_done
     fi
   ;;

   stop)
     stat_busy "Stopping LISa"
     kill -9 `pidof /opt/kde/bin/lisa` &>/dev/null
     rm_daemon lisa
     stat_done
   ;;

   restart)
     stat_busy "Restarting LISa ..."
     $0 stop
     $0 start
     stat_done
   ;;

   *)
     echo "usage: $0 {start|stop|restart}"
 esac