post_install() {
  if grep -w "audio" /etc/passwd &> /dev/null; then
    sed -i 's/audio//' /etc/conf.d/jack
    echo "==> It appears the system already has a user named 'audio'."
    echo "==> Please edit /etc/conf.d/jack and change the value of"
    echo "==> JACK_PROMISCUOUS_USER."
  fi
}

post_upgrade() {
  if grep -w "audio" /etc/passwd &> /dev/null; then
    echo "==> It appears the system already has a user named 'audio'"
    echo "==> Please edit /etc/conf.d/jack and change the value of"
    echo "==> JACK_PROMISCUOUS_USER."
    echo
    echo "==> You can ignore this if you received this message before"
    echo "==> and have already taken the necessary steps to rectify"
    echo "==> the problem."
  fi
}

pre_remove() {
  . /etc/conf.d/jack
  /etc/rc.d/jack stop &> /dev/null
  [ $JACK_PROMISCUOUS_SERVER -eq 1 ] && userdel $JACK_PROMISCUOUS_USER &> /dev/null
  return 0
}

# vim:set ts=2 sw=2 et:
