#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

get_jabber_pid() {
	echo `ps ax | grep /usr/bin/jabberd | grep perl | awk '{ print $1 }'`
}

case "$1" in
  start)
    stat_busy "Starting Jabber daemon"
		PID=`get_jabber_pid`
    if [ -z "$PID" ]; then
       /usr/bin/jabberd& &> /dev/null
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        sleep 1 # wait on children
        echo `get_jabber_pid` > /var/run/jabberd/jabberd.pid
        add_daemon jabberd
  			sleep 1
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping Jabber daemon"
		PID=`get_jabber_pid`
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    sleep 2
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      rm -f /var/run/jabberd/jabberd.pid &> /dev/null
      rm_daemon jabberd
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
