infodir=/usr/share/info
filelist=(wxmaxima.info.gz)

post_install() {
  update-desktop-database -q
  update-mime-database usr/share/mime

  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install
}

post_remove () {
  update-desktop-database -q
  update-mime-database usr/share/mime

  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}


