pkgname=gnome-bluetooth

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  if [ -f usr/share/gconf/schemas/${pkgname}.schemas ]; then
    usr/sbin/gconfpkg --uninstall ${pkgname}
  fi
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
