post_install() {
if [ ! -f /boot/grub/grub.cfg ]; then
 echo -n "Generating grub.cfg config file... "
 grub-mkconfig -o /boot/grub/grub.cfg 2> /dev/null
 echo "done."
fi
cat << EOF 
 Please verify the config file installed in /boot/grub/grub.cfg
 For more information and additional config settings please see http://wiki.archlinux.org/index.php/GRUB2

 GRUB2 is still expiremental and under heavy development!. 
 Only install it if you know what you are doing. 

EOF

}


