post_install() {
  update-desktop-database -q
  update-mime-database usr/share/mime &> /dev/null
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_upgrade() {
  update-desktop-database -q
  update-mime-database usr/share/mime &> /dev/null
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_remove() {
  update-desktop-database -q
  update-mime-database usr/share/mime &> /dev/null
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}
