post_install() {
  echo "-> Bitlbee can run through xinetd or as a daemon for now."
  if [ ! `grep bitlbee /etc/group` ]; then
    groupadd -g 65 bitlbee &>/dev/null;
  fi

  id bitlbee &>/dev/null || \
    useradd -u 65 -g bitlbee -d /var/lib/bitlbee -s /bin/false bitlbee
}

post_upgrade() {
  post_install $1
}

post_remove() {
  getent passwd bitlbee >/dev/null 2>&1 && userdel bitlbee
  getent group bitlbee >/dev/null 2>&1 && groupdel bitlbee
}
