# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Maintainer: Tom K <tomk@runbox.com>
pkgname=mod_perl
pkgver=2.0.3
pkgrel=3
pkgdesc="Apache module that embeds the Perl interpreter within the server"
url="http://search.cpan.org/~PGOLLUCCI/mod_perl"
depends=('perl' 'apache' 'db>=4.6' 'apr-util')
license="GPL"
arch=('i686' 'x64_86')
source=(http://www.cpan.org/authors/id/P/PG/PGOLLUCCI/mod_perl-$pkgver.tar.gz) 
md5sums=('b40e2adf67c6be15a0041af1c67b6997')

build() {
  cd  $startdir/src/mod_perl-$pkgver
  eval `perl -V:archname`
  # Force module installation to "current" perl directories.
  /usr/bin/perl Makefile.PL MP_APXS=/usr/sbin/apxs \
      INSTALLARCHLIB=/usr/lib/perl5/current/${archname} \
      INSTALLSITELIB=/usr/lib/perl5/site_perl/current \
      INSTALLSITEARCH=/usr/lib/perl5/site_perl/current/${archname}
  /usr/bin/make || return 1
  /usr/bin/make DESTDIR=$startdir/pkg install
  # remove perllocal.pod, .packlist, and empty dirs:
  /usr/bin/find $startdir/pkg -name '.packlist' -exec rm  '{}' \;
  /usr/bin/find $startdir/pkg -name 'perllocal.pod' -exec rm  '{}' \;
  /usr/bin/find $startdir/pkg -depth -type d -empty -exec rmdir '{}' \;
}
