# arg 1:  the new package version
post_install() {
  if [ -e /var/lib/pacman/local/gnome-session* ]; then
  mkdir -p /usr/share/applications
  cp -uf /usr/share/OOodi2/ooodi.desktop /usr/share/applications    
  echo " installing gnome menu items"
  fi
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install 
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
