# arg 1:  the new package version
post_install() {
    if [ -z "`grep '^nsvsd::' /etc/group`" ]; then
	groupadd -g 83 nsvsd
    fi
    if [ -z "`grep '^nsvsd:' /etc/passwd`" ]; then
	useradd -u 83 -d /tmp -g nsvsd -s /bin/false nsvsd
    fi
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
    post_install $1
}

# arg 1:  the old package version
pre_remove() {
    userdel nsvsd &> /dev/null
    groupdel nsvsd &> /dev/null
}

op=$1
shift

$op $*
