post_install() {
  echo "Updating desktop and mime database..."
  update-desktop-database -q
  echo -n "Updating vim help tags..."
  usr/bin/vim --noplugins -u NONE -U NONE \
    --cmd ":helptags usr/share/vim/doc" --cmd ":q" > /dev/null 2>&1
  echo "done."
}

post_upgrade() {
  post_install $1
}

post_remove() {
  echo -n "Updating desktop and mime database..."
  update-desktop-database
  echo "done."
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"

# vim:set ts=2 sw=2 et ft=sh:
