#!/bin/sh

build() {
    if command -v add_systemd_unit >/dev/null; then
        add_systemd_unit haveged-once.service
	add_symlink /usr/lib/systemd/system/sysinit.target.wants/haveged-once.service ../haveged-once.service
    else
        add_binary 'haveged'
        add_runscript
    fi
}

help() {
    cat <<HELPEOF
Haveged for early entropy and fast crng initialization.
HELPEOF
}
