scores=(
  'gweled.easy.scores'
  'gweled.timed.scores'
)

post_install() {
  for score in "${scores[@]}" ; do
    if [ -e "var/games/${score}" ]; then
      continue
    fi
    touch "var/games/${score}"
    chown root:games "var/games/${score}"
    chmod 664 "var/games/${score}"
  done
}

post_upgrade() {
  post_install $1
}

post_remove() {
  for score in "${scores[@]}" ; do
    rm -f "var/games/$score"
  done
}
