post_install() {
  post_upgrade

  cat << EOP
  Kismet has been installed with net_raw,net_admin capabilities capture helper
  executables for users in the 'kismet' group. This WILL ALLOW USERS IN THIS
  GROUP TO ALTER YOUR NETWORK INTERFACE STATES, but is more secure than running
  all of Kismet as root. ONLY users in this group will be able to run Kismet
  and capture from physical network devices.
EOP
}

post_upgrade() {
  for cap_bin in /usr/bin/kismet_cap_*; do
    setcap cap_net_raw,cap_net_admin=eip "${cap_bin}";
  done
}

# vim:set ts=2 sw=2 et:
