post_install () {
   cat << _EOF
  ==> make sure you use KernelModeSetting (KMS)
  ==> see http://wiki.archlinux.org/index.php/Nouveau#KMS for more
_EOF
}

post_upgrade() {
  if [ "`vercmp $2 0.0.15_git20100117-1`" -lt 0 ]; then
    cat << _EOF
  ==> ATTENTION: Usermode support has been dropped
  ==> make sure you use KernelModeSetting (KMS)
  ==> see http://wiki.archlinux.org/index.php/Nouveau#KMS for more
_EOF
 fi
}
