post_install() {
  post_upgrade $1 0
}

post_upgrade() {
  if (( $(vercmp $2 2.6.5-1) < 0 )); then
    cat <<MSG
  Subpixel hinting mode can be chosen by setting the right value in
  your environment, for example /etc/environment or ~/.pam_environment .

  Available settings:
      FT2_SUBPIXEL_HINTING=0  # Classic mode (default in 2.6)
      FT2_SUBPIXEL_HINTING=1  # Infinality mode
      FT2_SUBPIXEL_HINTING=2  # Minimal mode (default in 2.7)
MSG
  fi
}
