post_install() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
    echo "To use Empathy you need to install at least one Telepathy connection manager."
}

post_upgrade() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

post_remove() {
    post_upgrade
}
