#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

# source application-specific settings
[ -f /etc/conf.d/autofs ] && . /etc/conf.d/autofs

if [ ! -z "$TIMEOUT" ]; then
  daemonoptions="--timeout=$TIMEOUT $daemonoptions"
fi

PID=`cat /var/run/autofs-running &> /dev/null`
case "$1" in
  start)
    stat_busy "Starting Automounter"
    [ -z "$PID" ] && /usr/sbin/automount $daemonoptions &> /dev/null &
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon autofs
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Automounter"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon autofs
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
