# arg 1:  the new package version
post_install() {
  echo "==> ivman: Check the configuration files under /etc/ivman/ "
  echo "==> and save them without the '.default' ending"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

pre_remove() {
  # remove users & groups
  /bin/true
}
op=$1
shift

$op $*
